Importar data

In [1]:
import pandas as pd
noSolutionDF = pd.read_csv('output_nosol.csv')
solutionDF = pd.read_csv('output_sol.csv')

Etiquetas

In [6]:
import numpy as np
noSolutionCount = noSolutionDF.shape[0]
solutionCount = solutionDF.shape[0]

print(noSolutionCount)
print(solutionCount)

noSolutionLabel = [0] * noSolutionCount  * 6
solutionLabel = [1] * solutionCount * 6
labels = noSolutionLabel + solutionLabel


Y = np.array(labels)

1339
1331
(2,)


X tableros

In [3]:
def Rotate_90(tablero):
    return np.rot90(tablero, k=1)

def Rotate_180(tablero):
    return np.rot90(tablero, k=2)

def Rotate_270(tablero):
    return np.rot90(tablero, k=3)

def FlipX(tablero):
    return np.fliplr(tablero)

def FlipY(tablero):
    return np.flipud(tablero)

boards = []

for indice, fila in noSolutionDF.iterrows():
    tableros_en_celda = fila['Board'].replace("\r", "").split('\n')
    tableros_en_celda = list(filter(lambda x: x != '', tableros_en_celda))
    tablero_matriz = [list(fila) for fila in tableros_en_celda]
    boards.append(tablero_matriz)
  
    
print("El tamaño de la lista `boards` es:", len(boards))
for indice, fila in solutionDF.iterrows():
    tableros_en_celda = fila['Board'].replace("\r", "").split('\n')
    tableros_en_celda = list(filter(lambda x: x != '', tableros_en_celda))
    tablero_matriz = [list(fila) for fila in tableros_en_celda]
    boards.append(tablero_matriz)

    # Data augmentation
aug_boards = []
for board in boards:
    board_np = np.array(board)
    aug_boards.append(board_np)  
    aug_boards.append(Rotate_90(board_np))  
    aug_boards.append(Rotate_180(board_np)) 
    aug_boards.append(Rotate_270(board_np))  
    aug_boards.append(FlipX(board_np))  
    aug_boards.append(FlipY(board_np))  

print("El tamaño de la lista `boards` es:", len(aug_boards))
with np.printoptions(threshold=np.inf):
    print(aug_boards[0])


# Imprie
'''for i, lista in enumerate(boards):
    print(f"Lista de tableros {i+1}:")
    for tablero in lista:
        print(tablero)
    print()  # Salto de línea entre listas de tablero'''

El tamaño de la lista `boards` es: 1339
El tamaño de la lista `boards` es: 16020
[['#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#']
 ['#' '#' '#' ' ' ' ' ' ' '#' '$' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '#']
 ['#' '#' '#' ' ' '$' ' ' '$' ' ' ' ' ' ' '$' ' ' '#' '$' ' ' '#']
 ['#' '#' '#' ' ' '#' '$' '#' ' ' '#' '#' '#' ' ' ' ' '$' ' ' '#']
 ['#' '#' '#' ' ' '#' ' ' '.' '.' '.' '.' '.' '#' '#' '$' '#' '#']
 ['#' '#' '#' ' ' ' ' '.' '.' '.' '+' '.' '.' ' ' ' ' '$' ' ' '#']
 ['#' '#' '#' '#' '$' '#' ' ' '.' '.' '.' '.' '#' ' ' '#' ' ' '#']
 ['#' ' ' ' ' ' ' ' ' '#' '#' '#' '#' ' ' '#' '$' '$' '$' ' ' '#']
 ['#' ' ' '$' '#' ' ' ' ' ' ' ' ' ' ' '$' ' ' '$' ' ' '#' ' ' '#']
 ['#' ' ' '$' ' ' '.' '.' '#' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '#']
 ['#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#']]


'for i, lista in enumerate(boards):\n    print(f"Lista de tableros {i+1}:")\n    for tablero in lista:\n        print(tablero)\n    print()  # Salto de línea entre listas de tablero'

Tableros a tensor

In [4]:
import numpy as np

def tablero_a_tensor(tablero):
    alto = len(tablero)
    ancho = len(tablero[0])
    tensor = np.zeros((alto, ancho, 7))

    for i in range(alto):
        for j in range(ancho):
            elemento = tablero[i][j]
            if elemento == '#':
                tensor[i, j, 0] = 1
            elif elemento == '$':
                tensor[i, j, 1] = 1
            elif elemento == '.':
                tensor[i, j, 2] = 1
            elif elemento == '@':
                tensor[i, j, 3] = 1
            elif elemento == '*':
                tensor[i, j, 4] = 1
            elif elemento == '+':
                tensor[i, j, 5] = 1
            elif elemento == ' ':
                tensor[i, j, 6] = 1
                
    return tensor


X = [tablero_a_tensor(tablero) for tablero in aug_boards]
print("Tensor")
with np.printoptions(threshold=np.inf):
    print(X[0])


max_height = max(tensor.shape[0] for tensor in X)
max_width = max(tensor.shape[1] for tensor in X)


X_padded = np.ones((len(X), max_height, max_width, 7))

for idx, tensor in enumerate(X):
    height = tensor.shape[0]
    width = tensor.shape[1]
    X_padded[idx, :height, :width, :] = tensor

with np.printoptions(threshold=np.inf):
    print(X_padded[0])


'''print("Dimensiones de X_padded:", X_padded.shape)

# Verificar las dimensiones de X y y
#print("Dimensiones de X:", X.shape)
print("Dimensiones de y:", Y.shape)'''

Tensor
[[[1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0.

'print("Dimensiones de X_padded:", X_padded.shape)\n\n# Verificar las dimensiones de X y y\n#print("Dimensiones de X:", X.shape)\nprint("Dimensiones de y:", Y.shape)'

FSN

In [5]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, GlobalAveragePooling2D, Dense, MaxPooling2D
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

X_train, X_test, Y_train, Y_test = train_test_split(X_padded, Y, test_size=0.2, random_state=23)
print(len(X_train), len(Y_train), len(X_test), len(Y_test))


input_shape = (None, None, 7)  
inputs = Input(shape=input_shape)

# Arq
x = Conv2D(filters=32, kernel_size=3, activation='relu', padding='same')(inputs)
x = Conv2D(filters=32, kernel_size=2, activation='relu', padding='same')(x)
x = Conv2D(filters=64, kernel_size=3, activation='relu', padding='same')(x)
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
outputs = Dense(1, activation='sigmoid')(x)


model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()
#model.fit(X_train, Y_train, epochs=300, batch_size=32, validation_data=(X_test, Y_test))

# History
history = model.fit(X_train, Y_train, epochs=50, batch_size=32, validation_data=(X_test, Y_test))

# Graficar
plt.figure(figsize=(12, 6))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Training and Validation Accuracy')
plt.legend()
plt.show()


12816 12816 3204 3204


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, None, None, 7)  │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, None, None, 32) │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, None, None, 32) │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, None, None, 64) │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, None, None, 64) │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, None, None, 1)  │            65 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1)              │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28,897 (112.88 KB)

 Trainable params: 28,897 (112.88 KB)

 Non-trainable params: 0 (0.00 B)

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 15, 16, 8, 8, 17, 10, 10, 7, 8, 9, 8, 8, 12, 6, 10, 29, 9, 10, 13, 10, 8, 10, 8, 8, 11, 12, 8, 9, 7, 9, 22, 12, 11, 16, 9, 11, 21, 11, 8, 8, 11, 16, 11, 11, 10, 9, 10, 13, 13, 9, 8, 9, 15, 7, 8, 9, 9, 16, 9, 10, 7, 8, 11, 19, 9, 11, 10, 11, 11, 10, 10, 8, 14, 27, 10, 17, 11, 8, 8, 15, 9, 9, 9, 8, 8, 11, 8, 12, 10, 12, 21, 19, 9, 9, 16, 9, 10, 8, 9, 10, 7, 10, 13, 9, 8, 7, 15, 8, 8, 20, 8, 19, 8, 16, 11, 16, 16, 18, 14, 22, 11, 11, 12, 10, 11, 9, 11, 9, 11, 10, 10, 8, 21, 10, 10, 7, 11, 9, 10, 8, 8, 8, 25, 13, 9, 9, 15, 8, 13, 14, 6, 8, 9, 15, 18, 9, 9, 10, 8, 8, 9, 9, 9, 9, 12, 13, 9, 7, 11, 7, 8, 12, 17, 8, 9, 13, 11, 7, 9, 9, 8, 17, 21, 9, 11, 10, 17, 7, 17, 10, 10, 15, 13, 7, 9, 8, 8, 9, 8, 8, 8, 15, 17, 7, 12, 13, 9, 8, 8, 10, 9, 9, 11, 7, 8, 9, 9, 9, 11, 9, 12, 9, 16, 15, 7, 9, 11, 10, 14, 9, 9, 11, 10, 8, 9, 8, 9, 17, 17, 14, 11, 13, 11, 11, 7, 12, 10, 13, 9, 9, 8, 10, 10, 10, 8, 8, 23, 9, 11, 9, 10, 9, 9, 8, 17, 11, 10, 7, 9, 11, 9, 27, 9, 8, 10, 9, 10, 11, 11, 9, 8, 19, 19, 11, 9, 10, 8, 11, 13, 15, 9, 13, 10, 29, 12, 10, 7, 14, 8, 8, 7, 10, 9, 8, 8, 10, 11, 10, 9, 9, 9, 17, 18, 8, 10, 11, 7, 13, 10, 10, 9, 8, 11, 10, 16, 9, 14, 13, 9, 18, 13, 10, 7, 13, 13, 10, 8, 7, 9, 10, 11, 9, 11, 19, 15, 10, 9, 16, 8, 8, 8, 11, 12, 9, 9, 15, 10, 11, 10, 9, 7, 14, 7, 11, 11, 17, 8, 20, 27, 10, 17, 9, 11, 9, 9, 8, 12, 11, 11, 11, 9, 8, 9, 9, 10, 9, 17, 15, 9, 11, 9, 8, 8, 9, 15, 13, 18, 11, 10, 7, 11, 10, 9, 8, 8, 8, 10, 10, 10, 20, 9, 13, 8, 10, 17, 10, 12, 9, 6, 8, 9, 9, 11, 9, 8, 7, 9, 7, 13, 17, 13, 9, 8, 9, 9, 11, 15, 9, 9, 10, 11, 7, 8, 8, 10, 11, 8, 8, 18, 11, 10, 8, 6, 17, 10, 7, 11, 6, 10, 11, 9, 10, 19, 12, 11, 15, 12, 8, 14, 9, 16, 8, 9, 8, 9, 8, 14, 10, 11, 10, 9, 7, 13, 8, 8, 9, 10, 9, 10, 17, 10, 8, 9, 7, 12, 17, 17, 10, 8, 11, 10, 15, 9, 9, 13, 10, 9, 8, 14, 8, 10, 17, 23, 7, 8, 9, 9, 9, 7, 7, 19, 7, 12, 8, 15, 9, 14, 8, 17, 10, 14, 8, 12, 13, 7, 8, 9, 9, 7, 10, 17, 9, 9, 9, 14, 15, 11, 9, 9, 23, 8, 10, 9, 9, 12, 13, 9, 11, 9, 8, 11, 8, 13, 11, 8, 8, 20, 13, 15, 10, 16, 11, 9, 9, 9, 9, 10, 17, 9, 8, 17, 10, 10, 9, 10, 11, 9, 10, 9, 13, 21, 8, 8, 9, 14, 9, 9, 9, 9, 10, 11, 7, 8, 19, 11, 10, 14, 10, 7, 9, 14, 13, 12, 10, 11, 8, 13, 7, 7, 9, 10, 10, 9, 9, 9, 17, 12, 9, 9, 10, 11, 11, 11, 9, 8, 10, 12, 11, 10, 10, 9, 14, 14, 9, 12, 8, 8, 13, 8, 9, 9, 9, 9, 11, 10, 13, 11, 10, 14, 11, 9, 16, 11, 8, 9, 9, 8, 9, 18, 13, 8, 9, 10, 8, 15, 8, 10, 18, 9, 9, 10, 8, 11, 7, 11, 8, 9, 9, 9, 9, 9, 10, 8, 12, 9, 9, 18, 6, 11, 10, 8, 8, 27, 9, 8, 9, 9, 10, 15, 9, 14, 13, 13, 8, 9, 9, 6, 14, 8, 8, 8, 7, 7, 11, 9, 7, 9, 8, 17, 9, 7, 10, 9, 10, 12, 8, 12, 16, 17, 8, 25, 8, 20, 8, 17, 9, 9, 10, 8, 14, 10, 11, 12, 17, 16, 14, 10, 10, 10, 8, 17, 8, 16, 8, 14, 8, 7, 10, 12, 9, 8, 9, 10, 11, 11, 12, 8, 16, 13, 9, 8, 8, 9, 18, 8, 8, 11, 12, 15, 9, 13, 8, 9, 20, 7, 30, 8, 8, 15, 16, 9, 8, 9, 7, 12, 11, 7, 9, 9, 7, 6, 10, 11, 17, 8, 13, 6, 8, 16, 9, 11, 11, 8, 9, 12, 7, 15, 16, 9, 9, 8, 9, 9, 7, 10, 14, 11, 9, 8, 10, 14, 10, 10, 13, 18, 9, 8, 9, 8, 7, 8, 9, 8, 10, 9, 10, 13, 9, 9, 9, 19, 10, 9, 15, 16, 17, 11, 9, 9, 8, 9, 9, 12, 10, 12, 17, 10, 12, 11, 13, 7, 20, 9, 10, 9, 12, 17, 7, 10, 11, 7, 9, 9, 16, 8, 8, 13, 9, 6, 9, 9, 10, 9, 10, 11, 9, 15, 13, 9, 8, 11, 9, 9, 18, 10, 17, 6, 8, 8, 10, 7, 9, 7, 12, 17, 8, 7, 9, 8, 10, 9, 8, 7, 9, 10, 9, 9, 10, 7, 9, 13, 9, 14, 8, 12, 18, 10, 8, 8, 7, 9, 12, 15, 12, 11, 7, 8, 8, 23, 12, 9, 10, 7, 7, 10, 8, 10, 11, 11, 8, 8, 9, 11, 8, 6, 10, 16, 7, 11, 8, 17, 11, 10, 8, 10, 11, 8, 17, 8, 11, 11, 10, 8, 25, 8, 13, 7, 8, 8, 15, 9, 10, 11, 10, 9, 18, 11, 18, 11, 17, 11, 12, 9, 9, 7, 10, 10, 9, 8, 11, 8, 11, 9, 14, 10, 14, 8, 19, 8, 11, 11, 8, 10, 9, 9, 8, 16, 10, 10, 16, 11, 8, 9, 10, 10, 9, 8, 10, 10, 10, 11, 10, 13, 11, 12, 10, 15, 10, 10, 9, 8, 11, 10, 9, 11, 10, 8, 10, 8, 12, 11, 9, 11, 8, 16, 8, 11, 12, 11, 11, 7, 9, 7, 11, 11, 9, 11, 16, 10, 15, 9, 10, 8, 13, 7, 9, 10, 8, 7, 7, 11, 9, 18, 14, 10, 8, 8, 9, 15, 29, 9, 16, 10, 8, 9, 10, 10, 16, 17, 9, 10, 9, 10, 26, 11, 10, 13, 10, 9, 10, 9, 9, 8, 9, 9, 9, 16, 8, 8, 8, 9, 9, 11, 8, 8, 8, 10, 9, 9, 17, 11, 9, 9, 11, 9, 8, 8, 10, 8, 7, 10, 12, 7, 10, 7, 11, 8, 9, 10, 8, 16, 11, 8, 11, 8, 9, 8, 9, 7, 9, 7, 10, 9, 12, 9, 8, 12, 11, 11, 8, 9, 16, 10, 9, 25, 19, 8, 8, 19, 9, 11, 15, 14, 9, 11, 8, 15, 8, 8, 8, 18, 10, 16, 8, 10, 9, 11, 10, 9, 7, 9, 10, 10, 12, 10, 15, 8, 9, 10, 10, 8, 14, 13, 8, 10, 9, 10, 14, 9, 10, 17, 27, 11, 7, 12, 9, 8, 12, 10, 8, 9, 11, 16, 26, 8, 9, 9, 9, 8, 10, 9, 12, 24, 9, 16, 9, 8, 11, 9, 15, 8, 8, 10, 10, 8, 7, 8, 17, 8, 7, 13, 13, 7, 9, 26, 7, 15, 7, 8, 13, 14, 12, 13, 10, 9, 10, 9, 10, 14, 9, 9, 8, 9, 9, 13, 11, 11, 10, 10, 10, 7, 10, 8, 13, 9, 10, 10, 10, 9, 9, 11, 9, 10, 11, 11, 11, 13, 9, 8, 7, 9, 7, 15, 11, 18, 8, 9, 15, 13, 20, 14, 12, 17, 12, 9, 8, 10, 10, 9, 10, 9, 10, 9, 17, 17, 10, 17, 16, 14, 8, 13, 7, 10, 8, 8, 9, 9, 10, 8, 7, 9, 8, 10, 16, 12, 7, 16, 11, 8, 21, 9, 10, 10, 8, 8, 6, 10, 8, 10, 13, 9, 9, 11, 8, 10, 6, 7, 10, 8, 9, 9, 9, 9, 9, 12, 9, 9, 8, 7, 9, 9, 7, 9, 8, 9, 9, 10, 9, 9, 15, 11, 11, 8, 17, 17, 9, 9, 15, 10, 8, 11, 20, 8, 11, 9, 9, 8, 11, 16, 9, 8, 10, 8, 9, 11, 9, 13, 11, 16, 12, 11, 11, 18, 10, 10, 12, 12, 10, 10, 7, 9, 17, 15, 12, 8, 14, 12, 9, 9, 9, 9, 19, 11, 9, 20, 10, 14, 8, 18, 8, 9, 8, 16, 9, 17, 9, 9, 15, 8, 15, 9, 11, 12, 8, 11, 11, 15, 10, 11, 17, 12, 8, 11, 16, 7, 7, 8, 8, 10, 18, 17, 9, 11, 8, 10, 9, 8, 8, 7, 12, 8, 8, 7, 9, 12, 8, 8, 10, 17, 11, 10, 9, 10, 11, 9, 17, 9, 10, 8, 9, 8, 8, 8, 15, 10, 8, 9, 9, 8, 13, 9, 8, 13, 12, 9, 8, 15, 20, 9, 9, 7, 17, 8, 7, 11, 8, 9, 11, 7, 13, 10, 9, 18, 12, 16, 15, 10, 9, 12, 9, 12, 8, 13, 9, 17, 14, 8, 11, 11, 15, 8, 8, 11, 8, 11, 18, 7, 10, 17, 17, 10, 9, 14, 7, 10, 18, 9, 7, 16, 8, 10, 11, 12, 8, 14, 10, 10, 11, 19, 11, 8, 9, 9, 17, 7, 9, 8, 12, 10, 11, 23, 21, 9, 9, 10, 10, 9, 15, 8, 9, 9, 9, 9, 8, 11, 8, 10, 11, 9, 7, 9, 11, 9, 10, 7, 7, 15, 9, 13, 9, 12, 19, 11, 13, 8, 9, 8, 7, 16, 8, 16, 15, 7, 8, 7, 9, 10, 10, 8, 14, 15, 13, 7, 9, 11, 11, 26, 9, 12, 8, 12, 32, 19, 13, 15, 9, 8, 8, 8, 8, 12, 13, 14, 9, 10, 15, 7, 8, 10, 17, 12, 10, 22, 8, 9, 8, 9, 11, 9, 9, 10, 11, 10, 7, 12, 9, 9, 16, 11, 10, 10, 9, 10, 7, 9, 9, 8, 7, 18, 8, 8, 9, 15, 14, 8, 11, 10, 10, 10, 8, 7, 10, 10, 8, 9, 8, 10, 7, 17, 9, 8, 10, 10, 17, 9, 9, 11, 9, 7, 8, 10, 8, 8, 10, 7, 12, 9, 15, 10, 12, 8, 8, 9, 8, 14, 9, 7, 23, 9, 8, 8, 8, 11, 10, 8, 9, 10, 10, 8, 8, 8, 10, 15, 9, 8, 14, 9, 17, 8, 13, 11, 12, 8, 8, 18, 8, 11, 13, 10, 8, 8, 13, 11, 9, 8, 10, 10, 8, 7, 14, 7, 10, 8, 17, 7, 10, 13, 12, 10, 9, 9, 11, 9, 11, 15, 14, 12, 12, 11, 8, 9, 9, 11, 7, 9, 7, 7, 10, 8, 15, 10, 9, 8, 9, 8, 12, 9, 10, 10, 11, 30, 10, 13, 20, 10, 10, 17, 12, 8, 8, 9, 20, 10, 10, 8, 8, 13, 12, 10, 11, 7, 10, 22, 11, 26, 12, 10, 10, 6, 9, 7, 11, 11, 8, 7, 12, 9, 9, 7, 10, 8, 7, 9, 9, 7, 11, 16, 15, 7, 16, 8, 9, 17, 8, 9, 9, 8, 12, 9, 11, 14, 11, 9, 8, 12, 10, 10, 8, 13, 11, 8, 8, 8, 13, 12, 10, 9, 11, 12, 6, 9, 9, 10, 9, 8, 11, 9, 8, 9, 10, 24, 12, 13, 17, 7, 15, 10, 8, 8, 10, 9, 8, 10, 14, 17, 16, 9, 8, 10, 9, 13, 8, 8, 7, 11, 12, 10, 11, 9, 21, 7, 10, 23, 13, 10, 10, 13, 18, 12, 7, 7, 8, 18, 11, 9, 7, 8, 9, 9, 15, 9, 11, 7, 18, 16, 9, 7, 11, 10, 8, 9, 7, 9, 11, 15, 18, 9, 11, 8, 9, 9, 8, 9, 10, 12, 13, 12, 11, 8, 8, 9, 8, 20, 14, 8, 6, 9, 8, 11, 17, 9, 12, 12, 11, 11, 19, 10, 10, 8, 8, 10, 9, 26, 12, 11, 13, 8, 12, 8, 9, 13, 10, 10, 11, 11, 9, 8, 10, 10, 6, 8, 9, 10, 8, 17, 14, 9, 9, 9, 11, 8, 23, 15, 18, 8, 11, 9, 9, 13, 8, 8, 10, 8, 9, 10, 9, 16, 8, 8, 9, 8, 11, 10, 9, 8, 7, 10, 8, 11, 25, 12, 11, 9, 11, 8, 6, 7, 8, 10, 8, 8, 12, 27, 9, 15, 11, 11, 8, 13, 9, 17, 10, 9, 10, 9, 7, 8, 12, 13, 18, 9, 11, 26, 10, 8, 8, 10, 11, 9, 10, 7, 24, 9, 8, 20, 7, 18, 9, 7, 9, 9, 13, 9, 8, 12, 8, 10, 11, 15, 13, 13, 13, 7, 9, 16, 21, 15, 8, 9, 17, 8, 10, 9, 8, 9, 15, 10, 8, 9, 11, 12, 9, 8, 11, 7, 8, 16, 17, 9, 9, 17, 9, 8, 12, 11, 10, 11, 8, 22, 9, 11, 12, 8, 11, 10, 9, 8, 9, 8, 8, 10, 8, 8, 16, 8, 14, 8, 10, 10, 20, 9, 11, 8, 11, 8, 9, 9, 8, 10, 10, 10, 12, 11, 13, 17, 9, 10, 8, 9, 12, 9, 9, 13, 9, 7, 8, 9, 11, 24, 21, 19, 9, 11, 8, 8, 15, 9, 8, 10, 8, 7, 7, 10, 11, 13, 10, 8, 16, 8, 17, 8, 21, 10, 10, 9, 7, 8, 13, 13, 9, 8, 17, 14, 12, 9, 9, 10, 9, 17, 10, 8, 9, 13, 7, 12, 14, 8, 12, 13, 10, 9, 7, 9, 8, 8, 8, 8, 9, 9, 9, 30, 10, 10, 14, 7, 10, 11, 26, 17, 13, 24, 11, 14, 9, 15, 10, 9, 8, 17, 10, 10, 18, 8, 11, 10, 18, 12, 8, 10, 8, 11, 8, 18, 12, 6, 10, 7, 17, 14, 9, 11, 9, 13, 15, 17, 10, 10, 11, 9, 11, 8, 10, 8, 10, 18, 10, 13, 8, 12, 8, 9, 9, 11, 11, 9, 15, 13, 10, 14, 9, 8, 12, 18, 15, 10, 10, 11, 10, 8, 10, 11, 8, 8, 19, 20, 11, 8, 10, 10, 11, 11, 10, 11, 11, 17, 9, 8, 14, 7, 10, 23, 9, 22, 12, 13, 9, 12, 9, 12, 10, 9, 18, 9, 15, 9, 13, 11, 9, 19, 8, 11, 10, 14, 9, 8, 10, 8, 9, 8, 9, 10, 8, 11, 8, 8, 8, 9, 8, 10, 7, 8, 15, 9, 10, 8, 18, 11, 8, 17, 9, 10, 5, 10, 9, 10, 9, 9, 29, 9, 8, 9, 10, 17, 12, 11, 8, 9, 8, 9, 11, 20, 12, 17, 9, 10, 11, 9, 10, 7, 8, 14, 7, 9, 7, 8, 7, 9, 10, 8, 12, 10, 8, 9, 16, 10, 14, 11, 10, 10, 8, 7, 8, 7, 9, 12, 12, 8, 19, 11, 12, 20, 13, 8, 9, 10, 14, 9, 13, 8, 9, 7, 7, 7, 9, 17, 9, 9, 10, 9, 15, 8, 14, 9, 8, 8, 15, 8, 7, 10, 10, 16, 8, 8, 9, 9, 9, 17, 9, 12, 11, 23, 17, 21, 10, 9, 9, 9, 12, 15, 7, 9, 9, 17, 16, 8, 9, 11, 9, 8, 9, 16, 11, 13, 10, 10, 8, 10, 15, 8, 7, 8, 17, 8, 14, 11, 10, 9, 9, 7, 12, 8, 20, 7, 10, 10, 9, 6, 9, 11, 13, 8, 8, 8, 8, 10, 8, 15, 14, 7, 9, 8, 15, 14, 9, 15, 8, 8, 8, 15, 16, 8, 9, 8, 10, 11, 16, 11, 9, 8, 10, 9, 10, 10, 11, 10, 8, 12, 11, 9, 10, 8, 11, 7, 9, 10, 21, 7, 9, 7, 10, 11, 8, 17, 11, 11, 8, 15, 8, 13, 15, 9, 10, 12, 11, 16, 9, 14, 18, 9, 9, 14, 16, 9, 9, 7, 12, 8, 7, 9, 11, 15, 8, 7, 11, 9, 10, 11, 8, 8, 9, 10, 8, 9, 10, 8, 10, 15, 12, 5, 22, 10, 8, 17, 7, 7, 17, 8, 11, 5, 11, 9, 11, 16, 18, 9, 9, 8, 11, 13, 8, 11, 16, 26, 10, 8, 8, 10, 11, 8, 10, 8, 10, 7, 7, 7, 9, 9, 9, 14, 7, 11, 13, 13, 8, 16, 8, 9, 12, 15, 9, 8, 11, 10, 8, 15, 8, 13, 9, 8, 9, 9, 7, 11, 8, 13, 14, 9, 15, 9, 12, 8, 8, 7, 7, 7, 10, 9, 6, 12, 9, 7, 9, 14, 12, 8, 11, 8, 14, 14, 8, 11, 17, 12, 8, 16, 13, 9, 9, 12, 9, 15, 8, 10, 12, 16, 10, 9, 7, 10, 13, 11, 12, 8, 23, 8, 9, 19, 13, 10, 11, 18, 10, 8, 11, 9, 10, 10, 10, 10, 26, 10, 9, 8, 7, 9, 14, 11, 9, 15, 8, 9, 11, 9, 10, 17, 8, 10, 9, 8, 9, 10, 8, 8, 8, 9, 9, 10, 9, 10, 9, 8, 9, 12, 9, 9, 8, 9, 8, 9, 11, 11, 8, 9, 11, 13, 12, 19, 15, 17, 8, 9, 16, 9, 18, 13, 8, 13, 13, 13, 22, 8, 12, 15, 12, 16, 7, 11, 9, 9, 9, 7, 11, 8, 8, 8, 8, 8, 11, 8, 14, 11, 10, 9, 10, 8, 11, 8, 14, 8, 6, 23, 9, 9, 10, 10, 8, 9, 9, 13, 15, 14, 10, 9, 10, 13, 8, 9, 10, 7, 10, 10, 9, 8, 8, 10, 7, 11, 11, 13, 7, 8, 9, 8, 9, 7, 8, 15, 10, 8, 10, 8, 12, 12, 10, 11, 9, 16, 10, 7, 13, 13, 9, 7, 17, 22, 8, 16, 9, 7, 26, 8, 9, 13, 17, 10, 7, 8, 13, 8, 7, 10, 9, 11, 10, 13, 12, 10, 7, 13, 8, 8, 8, 9, 11, 10, 7, 17, 8, 8, 9, 8, 8, 10, 8, 8, 14, 7, 7, 16, 11, 11, 15, 8, 9, 10, 23, 17, 23, 13, 10, 12, 7, 9, 11, 10, 9, 7, 9, 9, 10, 9, 8, 11, 10, 10, 16, 11, 19, 16, 18, 9, 7, 9, 8, 8, 15, 7, 13, 14, 8, 8, 7, 11, 13, 10, 8, 9, 9, 17, 10, 13, 9, 10, 11, 16, 8, 9, 7, 6, 12, 24, 11, 10, 8, 9, 13, 8, 7, 17, 17, 7, 12, 10, 20, 9, 9, 17, 8, 10, 10, 18, 8, 10, 13, 10, 18, 7, 8, 13, 17, 8, 11, 9, 17, 11, 13, 9, 10, 8, 7, 15, 10, 7, 20, 16, 6, 18, 9, 7, 11, 13, 10, 17, 17, 11, 14, 8, 13, 13, 7, 11, 10, 15, 8, 20, 10, 16, 7, 13, 8, 9, 9, 13, 9, 9, 8, 16, 8, 12, 10, 9, 10, 10, 10, 20, 17, 10, 7, 8, 9, 9, 18, 8, 9, 8, 10, 9, 8, 10, 7, 8, 8, 14, 17, 8, 7, 10, 29, 9, 8, 8, 7, 10, 15, 9, 9, 8, 10, 8, 11, 9, 8, 8, 6, 8, 8, 13, 8, 8, 10, 11, 9, 10, 9, 7, 11, 11, 10, 18, 11, 10, 19, 8, 7, 12, 8, 21, 8, 10, 9, 9, 9, 11, 11, 15, 20, 8, 9, 10, 6, 8, 8, 9, 8, 11, 17, 23, 9, 7, 15, 8, 11, 10, 16, 12, 9, 7, 18, 8, 10, 10, 13, 15, 11, 7, 9, 9, 10, 19, 10, 8, 7, 9, 9, 13, 10, 8, 7, 7, 8, 14, 8, 9, 10, 9, 9, 10, 9, 12, 9, 8, 10, 10, 7, 7, 8, 8, 12, 10, 8, 8, 10, 7, 19, 9, 16, 9, 8, 8, 7, 8, 16, 11, 9, 11, 13, 9, 10, 17, 9, 22, 14, 11, 10, 8, 12, 11, 8, 14, 11, 9, 8, 8, 7, 21, 9, 11, 9, 11, 8, 8, 8, 10, 10, 15, 13, 8, 9, 10, 12, 10, 7, 9, 9, 10, 12, 9, 8, 14, 21, 10, 13, 13, 10, 16, 8, 9, 9, 10, 17, 11, 10, 12, 14, 11, 21, 11, 14, 14, 7, 9, 18, 10, 8, 8, 9, 11, 8, 5, 11, 10, 17, 11, 12, 10, 20, 8, 11, 9, 8, 14, 10, 11, 8, 10, 12, 11, 11, 17, 9, 8, 8, 9, 10, 10, 9, 9, 9, 9, 16, 9, 8, 9, 17, 9, 9, 9, 8, 13, 20, 12, 10, 10, 11, 9, 12, 17, 10, 8, 9, 13, 14, 10, 9, 10, 17, 10, 10, 10, 8, 15, 9, 8, 8, 11, 8, 10, 11, 10, 10, 10, 11, 8, 8, 13, 9, 8, 8, 13, 20, 8, 10, 11, 9, 8, 8, 9, 9, 23, 12, 9, 7, 11, 8, 9, 10, 9, 9, 19, 9, 9, 8, 9, 9, 8, 17, 8, 8, 10, 17, 12, 9, 9, 7, 7, 8, 15, 7, 15, 14, 17, 9, 11, 10, 18, 8, 13, 10, 7, 18, 8, 10, 11, 11, 12, 10, 9, 9, 13, 27, 9, 8, 16, 11, 10, 9, 20, 9, 9, 9, 19, 22, 8, 8, 9, 16, 10, 9, 13, 21, 11, 13, 9, 11, 8, 15, 9, 8, 8, 7, 8, 15, 8, 10, 8, 9, 9, 9, 9, 6, 17, 9, 8, 12, 9, 6, 8, 8, 18, 9, 13, 12, 7, 11, 9, 8, 11, 10, 10, 17, 13, 9, 16, 11, 11, 8, 17, 18, 11, 10, 8, 17, 9, 12, 11, 11, 10, 9, 17, 8, 8, 11, 8, 8, 9, 9, 10, 16, 8, 9, 8, 16, 10, 24, 7, 8, 9, 10, 8, 12, 18, 13, 20, 15, 16, 10, 13, 9, 10, 9, 12, 9, 7, 17, 17, 9, 19, 11, 11, 15, 9, 9, 8, 34, 9, 7, 10, 9, 12, 16, 8, 11, 6, 11, 11, 8, 6, 11, 18, 16, 8, 9, 11, 9, 8, 8, 13, 16, 9, 8, 10, 20, 8, 19, 8, 11, 8, 10, 10, 8, 9, 8, 8, 9, 11, 10, 13, 10, 12, 9, 10, 9, 7, 15, 21, 9, 10, 10, 10, 14, 15, 8, 7, 16, 10, 8, 16, 8, 10, 9, 8, 9, 9, 9, 10, 9, 18, 11, 9, 8, 8, 16, 7, 8, 9, 10, 8, 9, 8, 10, 12, 14, 10, 9, 12, 7, 11, 10, 11, 10, 8, 10, 11, 7, 13, 10, 7, 30, 12, 8, 11, 14, 18, 8, 10, 7, 9, 9, 9, 8, 14, 7, 9, 10, 9, 10, 18, 9, 10, 9, 10, 10, 11, 23, 9, 11, 9, 12, 9, 9, 10, 12, 17, 11, 9, 11, 8, 11, 9, 12, 13, 13, 10, 13, 10, 8, 9, 7, 9, 15, 9, 15, 9, 7, 8, 7, 17, 10, 9, 13, 8, 11, 8, 23, 8, 10, 12, 8, 9, 9, 8, 7, 8, 11, 15, 8, 10, 8, 9, 7, 10, 8, 9, 8, 10, 9, 10, 10, 10, 9, 8, 17, 25, 14, 11, 9, 13, 16, 8, 10, 18, 8, 16, 11, 15, 8, 10, 21, 10, 9, 9, 9, 10, 11, 11, 8, 11, 10, 9, 10, 17, 10, 8, 7, 10, 13, 11, 9, 8, 11, 9, 11, 11, 17, 7, 10, 9, 10, 18, 7, 13, 7, 11, 10, 15, 8, 10, 17, 18, 12, 9, 11, 15, 9, 8, 10, 7, 12, 14, 13, 10, 11, 10, 12, 17, 10, 13, 10, 12, 19, 10, 21, 10, 8, 8, 10, 20, 10, 14, 9, 13, 6, 8, 10, 10, 8, 13, 8, 10, 13, 15, 13, 8, 7, 8, 17, 10, 8, 30, 11, 9, 17, 10, 7, 9, 9, 8, 17, 10, 10, 8, 7, 11, 10, 8, 25, 10, 17, 8, 8, 9, 9, 12, 8, 9, 14, 8, 11, 14, 10, 10, 8, 9, 10, 8, 7, 12, 20, 9, 18, 9, 10, 7, 9, 8, 11, 14, 8, 11, 15, 9, 16, 8, 10, 11, 7, 17, 8, 20, 17, 13, 8, 8, 16, 13, 10, 14, 7, 8, 8, 11, 10, 12, 10, 8, 11, 21, 10, 7, 20, 9, 8, 8, 10, 8, 20, 6, 7, 20, 8, 9, 17, 16, 17, 9, 10, 8, 8, 14, 7, 10, 17, 22, 8, 9, 19, 8, 13, 9, 10, 10, 8, 20, 10, 9, 9, 12, 8, 7, 7, 11, 8, 6, 10, 8, 8, 11, 12, 10, 11, 12, 9, 9, 12, 9, 9, 8, 11, 10, 11, 11, 22, 8, 8, 8, 8, 10, 12, 6, 8, 8, 30, 8, 8, 11, 9, 10, 9, 8, 11, 8, 10, 14, 11, 7, 11, 12, 8, 10, 7, 11, 10, 28, 23, 17, 8, 9, 9, 10, 9, 8, 19, 9, 9, 15, 10, 8, 8, 10, 30, 11, 8, 10, 16, 17, 19, 9, 15, 9, 7, 12, 8, 7, 12, 10, 8, 16, 11, 15, 9, 7, 8, 8, 13, 12, 11, 9, 9, 10, 10, 13, 13, 8, 7, 7, 9, 15, 9, 9, 22, 9, 6, 10, 8, 14, 15, 10, 10, 8, 11, 9, 11, 16, 11, 18, 12, 15, 18, 19, 9, 7, 8, 9, 14, 8, 13, 17, 10, 11, 8, 16, 9, 18, 12, 15, 8, 15, 8, 6, 8, 8, 11, 9, 15, 17, 8, 8, 8, 14, 17, 9, 9, 12, 11, 8, 9, 8, 9, 15, 11, 10, 8, 10, 9, 9, 11, 10, 9, 9, 7, 8, 11, 10, 10, 10, 12, 12, 9, 7, 12, 17, 15, 10, 13, 8, 8, 8, 11, 12, 16, 8, 8, 8, 11, 15, 8, 25, 12, 17, 8, 9, 17, 8, 9, 9, 11, 10, 11, 10, 16, 9, 19, 9, 14, 12, 11, 8, 13, 8, 13, 9, 9, 8, 10, 10, 17, 11, 7, 12, 16, 8, 12, 9, 10, 20, 9, 25, 8, 21, 7, 9, 9, 9, 8, 9, 10, 11, 10, 11, 8, 10, 12, 11, 9, 9, 9, 10, 10, 9, 8, 17, 8, 15, 10, 8, 9, 9, 17, 8, 8, 17, 9, 7, 8, 11, 8, 8, 8, 7, 8, 17, 17, 10, 7, 13, 9, 8, 15, 10, 9, 8, 9, 9, 11, 12, 10, 10, 17, 7, 7, 18, 16, 12, 9, 10, 9, 13, 7, 11, 9, 10, 10, 8, 9, 9, 14, 8, 9, 10, 9, 13, 17, 14, 10, 10, 18, 8, 10, 12, 8, 9, 10, 10, 10, 10, 7, 15, 10, 9, 11, 8, 9, 10, 15, 12, 8, 18, 9, 10, 8, 10, 10, 8, 9, 13, 11, 8, 9, 8, 10, 11, 8, 13, 12, 9, 11, 11, 16, 7, 11, 8, 16, 7, 25, 9, 17, 13, 19, 7, 17, 9, 14, 8, 16, 9, 11, 10, 9, 8, 15, 9, 17, 18, 9, 14, 10, 9, 12, 8, 9, 17, 11, 12, 11, 10, 10, 10, 7, 7, 9, 17, 11, 7, 12, 10, 8, 7, 10, 9, 8, 14, 11, 10, 9, 10, 10, 12, 9, 9, 13, 10, 16, 15, 9, 10, 11, 9, 15, 10, 7, 7, 11, 14, 9, 10, 11, 10, 17, 7, 14, 10, 13, 9, 8, 10, 8, 8, 11, 17, 9, 8, 9, 9, 9, 9, 8, 7, 12, 7, 8, 11, 7, 9, 13, 14, 9, 9, 16, 9, 6, 9, 8, 10, 8, 7, 10, 9, 17, 8, 10, 13, 9, 17, 13, 9, 9, 10, 7, 9, 18, 30, 13, 12, 8, 10, 11, 12, 7, 14, 10, 20, 12, 13, 9, 13, 9, 12, 10, 8, 12, 9, 6, 9, 7, 8, 19, 9, 17, 10, 14, 6, 9, 7, 24, 10, 6, 8, 18, 12, 10, 17, 12, 12, 16, 8, 16, 19, 11, 17, 9, 19, 9, 10, 11, 10, 18, 9, 11, 10, 8, 11, 11, 15, 13, 10, 7, 15, 7, 8, 11, 12, 9, 9, 9, 10, 12, 10, 7, 7, 8, 8, 13, 6, 10, 9, 8, 13, 9, 18, 8, 9, 9, 10, 8, 12, 9, 8, 8, 18, 17, 10, 11, 11, 11, 29, 9, 10, 7, 7, 16, 9, 15, 17, 11, 8, 9, 13, 9, 10, 13, 12, 15, 10, 17, 7, 9, 9, 24, 9, 19, 9, 17, 11, 8, 11, 10, 16, 9, 12, 9, 10, 7, 5, 10, 11, 9, 9, 11, 9, 17, 11, 9, 13, 15, 9, 10, 10, 11, 9, 9, 10, 8, 10, 13, 10, 21, 7, 10, 9, 8, 10, 11, 6, 10, 9, 9, 15, 7, 11, 8, 9, 8, 13, 13, 10, 9, 10, 9, 8, 9, 7, 19, 7, 10, 13, 10, 27, 9, 11, 11, 8, 17, 8, 10, 11, 10, 8, 10, 9, 9, 9, 10, 10, 14, 9, 10, 7, 10, 16, 7, 15, 8, 9, 9, 8, 17, 7, 9, 8, 10, 14, 9, 19, 10, 8, 18, 10, 7, 13, 11, 22, 9, 13, 16, 10, 11, 7, 9, 8, 9, 10, 8, 11, 10, 8, 10, 12, 15, 11, 10, 9, 9, 7, 15, 11, 8, 9, 10, 10, 7, 14, 17, 8, 9, 15, 8, 14, 15, 13, 7, 14, 11, 9, 19, 14, 12, 8, 9, 15, 10, 12, 10, 8, 16, 8, 8, 9, 13, 12, 13, 14, 10, 9, 10, 16, 7, 9, 11, 9, 17, 8, 8, 9, 13, 8, 15, 17, 10, 8, 9, 17, 10, 13, 8, 16, 8, 8, 9, 9, 10, 9, 8, 13, 12, 17, 8, 15, 9, 9, 7, 10, 16, 7, 9, 24, 10, 10, 11, 14, 9, 16, 8, 15, 9, 11, 13, 9, 10, 8, 12, 10, 9, 13, 13, 11, 10, 15, 7, 12, 12, 16, 20, 8, 7, 10, 16, 11, 7, 8, 11, 12, 7, 13, 7, 8, 8, 11, 11, 10, 9, 8, 8, 18, 8, 8, 9, 16, 8, 7, 14, 11, 9, 7, 11, 10, 15, 10, 8, 10, 8, 13, 9, 8, 7, 9, 9, 8, 9, 9, 17, 7, 8, 8, 17, 8, 11, 15, 10, 10, 11, 15, 10, 9, 7, 8, 14, 12, 10, 9, 9, 11, 9, 9, 15, 11, 11, 8, 15, 7, 15, 10, 11, 10, 9, 8, 8, 15, 12, 10, 15, 13, 9, 11, 9, 16, 16, 7, 7, 16, 9, 19, 8, 17, 12, 8, 10, 11, 13, 8, 9, 10, 10, 8, 10, 10, 19, 11, 8, 7, 8, 10, 8, 14, 9, 11, 8, 12, 9, 7, 9, 15, 13, 10, 15, 15, 9, 10, 8, 7, 10, 9, 15, 16, 9, 12, 18, 17, 10, 12, 17, 8, 9, 14, 10, 6, 15, 10, 9, 9, 10, 10, 12, 11, 10, 7, 7, 8, 9, 8, 10, 8, 12, 7, 10, 10, 10, 12, 12, 15, 8, 14, 15, 9, 13, 11, 9, 10, 7, 7, 8, 11, 10, 8, 20, 10, 9, 10, 11, 18, 9, 11, 8, 11, 9, 14, 17, 14, 16, 8, 8, 20, 10, 16, 8, 10, 14, 10, 8, 9, 10, 8, 11, 8, 26, 15, 15, 10, 9, 8, 7, 9, 10, 12, 9, 9, 8, 7, 14, 8, 13, 27, 11, 8, 9, 10, 8, 17, 10, 19, 16, 11, 17, 10, 15, 8, 10, 17, 8, 11, 9, 10, 13, 9, 9, 10, 12, 9, 9, 8, 10, 10, 13, 8, 7, 10, 10, 9, 9, 10, 10, 15, 10, 9, 10, 9, 9, 8, 11, 9, 11, 9, 19, 7, 9, 9, 10, 10, 10, 11, 11, 9, 9, 8, 11, 11, 11, 17, 9, 9, 8, 9, 10, 11, 10, 11, 13, 8, 7, 9, 7, 11, 8, 10, 7, 10, 16, 17, 10, 8, 15, 10, 14, 8, 17, 8, 11, 8, 21, 10, 9, 9, 7, 6, 9, 9, 8, 9, 8, 8, 8, 10, 9, 8, 8, 8, 10, 16, 11, 9, 8, 9, 18, 17, 10, 9, 11, 9, 9, 12, 8, 12, 9, 10, 18, 14, 9, 11, 9, 12, 10, 10, 21, 8, 9, 8, 10, 9, 8, 9, 15, 15, 8, 10, 18, 9, 10, 11, 11, 8, 9, 8, 10, 11, 9, 18, 8, 10, 10, 12, 8, 11, 8, 8, 16, 9, 10, 12, 7, 10, 9, 10, 14, 8, 17, 16, 12, 10, 9, 13, 8, 8, 11, 13, 7, 10, 13, 9, 9, 12, 20, 9, 13, 9, 9, 11, 9, 7, 8, 8, 7, 9, 11, 7, 9, 10, 9, 13, 7, 8, 12, 15, 8, 7, 10, 23, 11, 10, 10, 8, 9, 9, 15, 9, 8, 10, 10, 8, 8, 13, 10, 7, 8, 11, 10, 8, 8, 9, 9, 11, 9, 9, 10, 10, 9, 11, 9, 8, 9, 8, 15, 18, 9, 9, 9, 16, 11, 9, 8, 7, 17, 8, 8, 11, 7, 9, 7, 8, 12, 10, 8, 9, 9, 10, 10, 15, 8, 12, 10, 7, 10, 9, 11, 7, 8, 10, 9, 10, 14, 9, 11, 10, 9, 8, 8, 8, 7, 9, 10, 9, 9, 12, 11, 8, 9, 8, 10, 10, 11, 11, 9, 22, 8, 16, 9, 8, 9, 9, 17, 8, 7, 23, 9, 14, 10, 17, 8, 18, 7, 9, 16, 10, 8, 8, 8, 10, 9, 14, 8, 9, 13, 7, 9, 7, 11, 9, 10, 7, 9, 15, 7, 9, 11, 17, 16, 10, 7, 10, 9, 10, 8, 12, 13, 16, 10, 10, 19, 11, 9, 18, 10, 11, 12, 8, 8, 13, 13, 13, 9, 12, 9, 17, 10, 10, 7, 7, 7, 10, 13, 10, 13, 12, 10, 10, 16, 7, 12, 9, 10, 10, 9, 8, 12, 16, 10, 15, 9, 9, 8, 11, 11, 12, 9, 11, 8, 8, 10, 11, 13, 9, 14, 10, 9, 9, 10, 8, 7, 9, 16, 12, 7, 17, 10, 13, 20, 11, 9, 10, 8, 8, 9, 20, 11, 18, 8, 13, 8, 13, 9, 13, 9, 13, 15, 9, 9, 9, 9, 9, 18, 9, 7, 11, 9, 10, 6, 12, 7, 9, 20, 6, 16, 11, 8, 9, 10, 8, 8, 9, 12, 7, 10, 7, 15, 15, 9, 14, 21, 21, 9, 8, 10, 12, 7, 11, 8, 7, 13, 16, 11, 7, 10, 8, 6, 8, 12, 17, 12, 11, 9, 16, 9, 10, 7, 15, 13, 9, 8, 11, 8, 10, 9, 9, 9, 8, 8, 10, 8, 10, 10, 9, 20, 9, 10, 9, 13, 25, 12, 9, 10, 8, 14, 8, 12, 22, 12, 8, 10, 12, 11, 9, 10, 8, 10, 14, 8, 10, 13, 9, 9, 9, 10, 21, 8, 15, 15, 10, 7, 8, 14, 16, 9, 7, 11, 14, 10, 24, 12, 10, 8, 11, 8, 17, 8, 8, 11, 8, 13, 8, 10, 23, 10, 17, 10, 8, 9, 10, 8, 11, 16, 13, 9, 17, 7, 12, 10, 15, 8, 15, 9, 8, 18, 10, 9, 9, 11, 10, 7, 11, 9, 11, 9, 7, 8, 9, 14, 11, 8, 9, 10, 7, 13, 10, 21, 13, 8, 15, 16, 10, 9, 15, 13, 10, 9, 9, 8, 18, 9, 9, 9, 14, 9, 8, 8, 8, 10, 7, 9, 11, 10, 12, 10, 11, 15, 9, 7, 10, 7, 10, 9, 8, 11, 9, 14, 9, 9, 8, 10, 9, 16, 10, 9, 7, 8, 10, 8, 10, 10, 7, 10, 13, 9, 8, 10, 9, 9, 12, 7, 9, 17, 9, 9, 17, 11, 8, 10, 8, 11, 10, 7, 7, 10, 13, 8, 10, 6, 9, 11, 6, 10, 17, 10, 13, 11, 9, 8, 8, 13, 17, 8, 10, 7, 12, 13, 16, 7, 10, 8, 10, 6, 7, 7, 9, 10, 8, 12, 7, 8, 8, 9, 8, 8, 13, 10, 18, 11, 10, 20, 20, 9, 8, 12, 10, 9, 10, 8, 9, 13, 9, 9, 8, 14, 10, 10, 9, 14, 9, 9, 10, 10, 11, 11, 10, 9, 12, 19, 8, 8, 8, 10, 17, 8, 9, 17, 19, 17, 10, 9, 16, 13, 9, 9, 10, 8, 9, 7, 13, 9, 9, 8, 8, 9, 10, 13, 7, 9, 10, 11, 16, 7, 9, 10, 9, 10, 18, 12, 9, 8, 7, 14, 18, 12, 20, 9, 10, 10, 13, 8, 10, 16, 8, 18, 9, 10, 15, 9, 9, 9, 7, 15, 8, 11, 10, 11, 10, 14, 10, 12, 9, 9, 11, 8, 6, 7, 7, 12, 12, 8, 13, 14, 9, 8, 11, 8, 14, 9, 16, 15, 7, 10, 8, 12, 7, 14, 8, 10, 11, 9, 8, 13, 10, 9, 8, 9, 21, 8, 8, 10, 10, 10, 8, 11, 9, 11, 8, 18, 10, 8, 13, 10, 9, 10, 10, 10, 7, 8, 13, 11, 8, 10, 7, 10, 17, 10, 11, 8, 13, 10, 9, 7, 9, 8, 11, 9, 11, 20, 9, 9, 18, 8, 13, 16, 7, 9, 8, 10, 21, 10, 8, 8, 10, 21, 8, 8, 8, 9, 8, 10, 10, 20, 15, 14, 7, 11, 9, 8, 15, 10, 12, 32, 9, 27, 9, 15, 18, 11, 8, 10, 10, 15, 11, 8, 11, 16, 13, 7, 8, 12, 10, 9, 9, 13, 10, 11, 9, 16, 17, 8, 11, 12, 9, 10, 11, 9, 9, 13, 18, 10, 8, 13, 7, 10, 19, 12, 9, 10, 9, 9, 16, 8, 7, 12, 10, 16, 8, 9, 9, 8, 37, 8, 15, 9, 9, 10, 8, 9, 8, 10, 8, 17, 9, 9, 8, 10, 10, 9, 15, 9, 7, 18, 9, 14, 18, 17, 15, 11, 9, 8, 12, 12, 10, 10, 13, 7, 10, 16, 15, 15, 7, 9, 7, 9, 11, 11, 7, 11, 17, 8, 17, 18, 16, 10, 9, 15, 8, 19, 11, 9, 11, 9, 7, 11, 10, 7, 9, 9, 8, 17, 10, 9, 11, 10, 11, 11, 10, 13, 10, 7, 16, 29, 9, 9, 10, 10, 9, 17, 10, 9, 9, 8, 11, 11, 8, 17, 14, 7, 10, 15, 11, 12, 9, 12, 10, 8, 9, 14, 12, 14, 8, 19, 9, 10, 8, 9, 9, 12, 9, 15, 9, 7, 20, 9, 11, 8, 17, 16, 11, 9, 9, 8, 14, 11, 17, 8, 7, 9, 10, 10, 14, 9, 10, 10, 11, 14, 8, 10, 10, 15, 9, 8, 13, 9, 17, 7, 12, 10, 9, 8, 13, 11, 9, 9, 17, 8, 16, 10, 11, 23, 8, 9, 13, 9, 13, 15, 9, 9, 11, 24, 8, 9, 10, 10, 13, 8, 8, 8, 8, 9, 10, 10, 15, 10, 8, 16, 10, 10, 10, 10, 9, 9, 10, 8, 11, 17, 9, 11, 9, 10, 9, 9, 8, 7, 8, 9, 7, 7, 20, 15, 21, 10, 9, 7, 11, 8, 10, 27, 8, 8, 19, 27, 8, 9, 13, 8, 9, 9, 11, 20, 7, 9, 9, 10, 9, 17, 9, 9, 10, 11, 11, 9, 12, 7, 12, 9, 5, 7, 9, 11, 10, 18, 13, 11, 14, 12, 9, 8, 10, 9, 17, 18, 10, 15, 10, 9, 9, 10, 14, 9, 10, 8, 16, 9, 5, 8, 8, 10, 11, 11, 8, 8, 9, 9, 10, 10, 8, 17, 9, 9, 8, 8, 10, 9, 8, 12, 21, 10, 9, 11, 10, 8, 8, 9, 11, 10, 8, 16, 13, 19, 8, 13, 14, 11, 8, 12, 8, 9, 9, 10, 11, 8, 7, 11, 10, 9, 9, 8, 10, 16, 15, 14, 11, 9, 12, 9, 11, 7, 11, 15, 8, 13, 11, 11, 7, 9, 10, 9, 8, 9, 24, 9, 10, 14, 8, 9, 15, 8, 11, 11, 16, 12, 9, 11, 8, 9, 11, 11, 22, 10, 36, 15, 10, 10, 10, 10, 18, 8, 10, 13, 13, 10, 10, 13, 18, 11, 7, 8, 11, 13, 9, 8, 10, 13, 10, 7, 12, 9, 8, 8, 8, 9, 9, 8, 9, 9, 13, 26, 8, 8, 8, 8, 9, 11, 14, 15, 10, 7, 9, 10, 11, 9, 9, 8, 9, 23, 10, 10, 13, 11, 12, 8, 10, 8, 8, 9, 20, 9, 9, 14, 10, 11, 8, 10, 8, 9, 10, 7, 11, 8, 20, 11, 10, 9, 8, 8, 8, 15, 8, 8, 10, 8, 10, 9, 9, 9, 8, 8, 13, 8, 8, 9, 9, 11, 8, 10, 7, 10, 10, 10, 23, 9, 11, 19, 7, 10, 9, 11, 11, 8, 9, 9, 7, 8, 8, 10, 9, 14, 9, 11, 9, 30, 15, 7, 11, 9, 8, 9, 11, 9, 10, 8, 13, 8, 19, 9, 9, 9, 11, 9, 10, 12, 8, 21, 8, 10, 8, 14, 9, 9, 8, 11, 6, 9, 9, 12, 9, 9, 8, 10, 10, 9, 9, 8, 9, 15, 8, 11, 11, 13, 8, 15, 15, 10, 10, 10, 13, 21, 8, 7, 9, 17, 9, 9, 20, 9, 9, 16, 8, 10, 8, 9, 8, 7, 9, 7, 11, 13, 9, 12, 13, 27, 9, 10, 12, 11, 9, 11, 12, 7, 13, 9, 11, 9, 15, 8, 7, 18, 12, 9, 8, 10, 10, 8, 8, 8, 6, 9, 7, 14, 7, 10, 9, 17, 11, 8, 8, 10, 7, 7, 9, 10, 13, 11, 11, 9, 9, 9, 18, 7, 13, 13, 10, 9, 12, 15, 11, 10, 10, 12, 10, 20, 9, 11, 9, 12, 10, 8, 9, 13, 8, 11, 13, 11, 9, 18, 9, 9, 16, 12, 16, 26, 8, 21, 9, 7, 11, 9, 13, 15, 14, 7, 10, 12, 11, 10, 15, 7, 8, 8, 9, 9, 15, 9, 15, 8, 9, 11, 10, 20, 10, 9, 9, 11, 9, 9, 11, 11, 16, 14, 13, 12, 9, 7, 12, 8, 10, 9, 10, 10, 17, 6, 10, 20, 7, 9, 16, 18, 11, 9, 10, 14, 14, 11, 14, 7, 8, 9, 11, 8, 9, 11, 8, 9, 15, 14, 22, 6, 18, 8, 7, 10, 9, 14, 11, 10, 13, 9, 9, 8, 10, 13, 7, 9, 12, 10, 14, 9, 8, 12, 8, 14, 9, 9, 19, 9, 8, 8, 8, 10, 7, 9, 10, 9, 16, 14, 9, 8, 11, 11, 13, 15, 8, 8, 11, 9, 15, 15, 8, 9, 10, 10, 9, 8, 10, 8, 7, 9, 9, 12, 9, 8, 9, 9, 7, 14, 10, 11, 8, 8, 6, 8, 10, 9, 9, 12, 8, 10, 15, 15, 17, 17, 9, 9, 13, 11, 15, 9, 9, 9, 9, 9, 7, 9, 8, 8, 15, 13, 16, 10, 8, 7, 8, 11, 9, 8, 10, 7, 7, 10, 13, 9, 9, 9, 10, 8, 11, 13, 18, 10, 8, 9, 8, 7, 10, 9, 7, 18, 19, 7, 14, 10, 9, 9, 13, 9, 11, 11, 8, 12, 10, 8, 13, 10, 10, 8, 7, 9, 11, 9, 8, 8, 9, 11, 8, 10, 10, 18, 7, 9, 11, 15, 8, 10, 9, 10, 11, 8, 7, 10, 8, 10, 13, 9, 10, 9, 9, 8, 13, 11, 8, 17, 14, 12, 13, 17, 8, 22, 23, 9, 13, 9, 12, 15, 8, 21, 17, 8, 9, 8, 7, 17, 7, 10, 9, 10, 8, 10, 9, 9, 9, 6, 10, 8, 7, 9, 15, 17, 9, 9, 8, 8, 8, 10, 9, 7, 11, 11, 11, 8, 8, 7, 9, 8, 12, 11, 11, 8, 9, 7, 9, 9, 12, 10, 14, 10, 7, 10, 8, 9, 9, 11, 12, 10, 9, 8, 21, 8, 9, 21, 6, 16, 11, 10, 9, 14, 10, 11, 13, 15, 9, 9, 8, 20, 8, 7, 9, 9, 9, 10, 9, 9, 9, 29, 17, 8, 7, 8, 11, 8, 8, 13, 13, 9, 17, 13, 9, 8, 11, 18, 8, 16, 7, 23, 10, 8, 10, 8, 9, 7, 9, 9, 9, 11, 9, 17, 8, 17, 8, 9, 10, 10, 11, 8, 15, 10, 9, 6, 14, 8, 8, 27, 13, 11, 11, 8, 8, 11, 18, 9, 14, 10, 17, 9, 11, 9, 8, 16, 11, 13, 12, 11, 11, 8, 8, 13, 17, 9, 9, 9, 9, 9, 9, 9, 9, 16, 17, 10, 7, 16, 10, 10, 9, 8, 8, 8, 22, 8, 8, 21, 10, 9, 8, 12, 10, 8, 11, 12, 13, 9, 22, 12, 12, 10, 10, 9, 7, 13, 19, 9, 9, 7, 10, 8, 8, 8, 10, 10, 9, 12, 9, 8, 10, 20, 7, 8, 12, 9, 9, 11, 12, 25, 13, 7, 9, 8, 10, 9, 12, 9, 20, 7, 7, 9, 11, 8, 11, 10, 19, 9, 9, 9, 9, 7, 15, 9, 11, 9, 7, 7, 12, 9, 18, 11, 10, 8, 17, 9, 10, 10, 8, 9, 27, 9, 8, 10, 11, 10, 14, 7, 15, 7, 18, 7, 10, 11, 9, 18, 7, 8, 18, 10, 10, 8, 10, 9, 10, 8, 17, 7, 10, 9, 10, 8, 9, 10, 11, 13, 10, 14, 16, 10, 8, 10, 7, 9, 9, 15, 9, 8, 16, 8, 13, 7, 13, 8, 11, 8, 10, 10, 11, 10, 9, 8, 11, 9, 9, 10, 14, 11, 7, 9, 8, 14, 11, 9, 8, 8, 13, 9, 10, 8, 8, 10, 11, 11, 11, 8, 8, 9, 7, 11, 9, 7, 14, 9, 10, 13, 7, 13, 7, 7, 8, 7, 7, 9, 13, 11, 15, 13, 9, 8, 21, 11, 7, 13, 7, 10, 10, 12, 9, 24, 10, 8, 9, 9, 9, 9, 8, 11, 10, 11, 20, 9, 13, 12, 8, 9, 9, 8, 7, 10, 11, 9, 15, 7, 10, 17, 9, 15, 15, 8, 9, 9, 17, 8, 8, 9, 8, 15, 8, 9, 8, 8, 9, 8, 7, 8, 27, 16, 12, 15, 9, 9, 10, 11, 10, 9, 9, 11, 11, 8, 10, 16, 12, 11, 10, 7, 8, 12, 13, 19, 11, 9, 11, 9, 11, 10, 8, 19, 17, 8, 11, 9, 7, 12, 13, 8, 9, 7, 30, 9, 16, 12, 17, 8, 9, 12, 9, 9, 13, 17, 9, 11, 9, 15, 9, 7, 9, 11, 9, 11, 12, 9, 11, 8, 18, 8, 7, 12, 19, 9, 10, 10, 22, 10, 10, 9, 10, 17, 14, 10, 10, 10, 7, 9, 18, 10, 11, 8, 8, 9, 8, 8, 11, 15, 13, 9, 13, 7, 16, 10, 14, 9, 13, 9, 9, 13, 13, 10, 10, 11, 13, 8, 9, 10, 9, 18, 12, 15, 13, 10, 8, 12, 10, 10, 9, 14, 11, 11, 8, 9, 14, 10, 9, 9, 9, 17, 9, 7, 23, 9, 13, 11, 8, 13, 9, 9, 10, 9, 11, 9, 9, 9, 10, 8, 15, 8, 13, 9, 9, 11, 9, 7, 9, 8, 10, 9, 10, 10, 10, 8, 8, 10, 10, 11, 8, 10, 15, 11, 9, 8, 11, 7, 18, 7, 8, 22, 19, 15, 8, 11, 10, 10, 8, 9, 10, 11, 15, 8, 12, 11, 10, 9, 12, 16, 7, 18, 11, 18, 11, 12, 11, 8, 10, 17, 10, 7, 10, 8, 13, 10, 11, 12, 9, 9, 10, 12, 9, 9, 17, 10, 11, 15, 14, 16, 9, 8, 9, 14, 7, 12, 12, 9, 16, 13, 11, 10, 12, 7, 8, 12, 8, 8, 10, 10, 27, 8, 9, 13, 22, 8, 11, 8, 7, 7, 7, 11, 10, 12, 9, 9, 10, 10, 13, 7, 9, 12, 11, 19, 10, 13, 16, 8, 21, 11, 8, 11, 9, 21, 8, 16, 8, 7, 17, 12, 11, 8, 6, 9, 9, 7, 11, 9, 10, 9, 7, 11, 17, 16, 9, 11, 10, 7, 9, 13, 15, 11, 8, 8, 12, 14, 17, 13, 8, 9, 15, 10, 10, 13, 10, 9, 9, 8, 10, 9, 11, 11, 13, 8, 9, 11, 15, 10, 9, 20, 8, 8, 14, 8, 10, 9, 13, 11, 18, 8, 8, 9, 7, 8, 17, 10, 8, 6, 9, 9, 8, 12, 12, 7, 10, 8, 12, 9, 8, 12, 9, 11, 9, 10, 9, 9, 10, 14, 11, 11, 10, 12, 9, 7, 5, 8, 12, 9, 22, 9, 16, 9, 10, 10, 9, 7, 10, 8, 8, 21, 9, 7, 14, 9, 18, 9, 18, 10, 8, 9, 8, 11, 9, 8, 6, 10, 14, 7, 9, 25, 9, 8, 17, 9, 8, 13, 12, 9, 11, 28, 12, 10, 9, 9, 13, 12, 10, 7, 9, 8, 10, 9, 13, 12, 8, 12, 8, 10, 12, 11, 9, 9, 9, 13, 11, 7, 7, 9, 15, 9, 9, 10, 9, 10, 10, 15, 10, 7, 12, 13, 9, 8, 8, 19, 11, 11, 12, 8, 12, 10, 10, 15, 8, 10, 11, 9, 13, 9, 9, 7, 9, 8, 17, 8, 11, 10, 9, 8, 8, 9, 11, 7, 13, 13, 8, 9, 8, 9, 17, 8, 8, 9, 10, 12, 9, 7, 11, 19, 8, 11, 8, 8, 10, 21, 9, 9, 8, 8, 9, 9, 7, 8, 9, 9, 11, 13, 9, 11, 8, 9, 7, 8, 11, 11, 23, 8, 8, 9, 8, 8, 10, 7, 9, 9, 8, 13, 8, 18, 23, 9, 14, 8, 18, 10, 10, 12, 21, 13, 7, 11, 17, 11, 11, 9, 14, 11, 9, 9, 9, 10, 9, 9, 11, 15, 10, 10, 8, 9, 8, 9, 9, 9, 7, 17, 9, 9, 12, 7, 10, 9, 7, 9, 10, 9, 11, 10, 12, 12, 17, 9, 18, 9, 7, 9, 17, 12, 13, 8, 11, 20, 8, 7, 9, 9, 8, 7, 7, 8, 11, 7, 11, 11, 10, 8, 12, 13, 20, 10, 14, 7, 9, 11, 8, 10, 9, 16, 9, 9, 9, 12, 21, 9, 15, 9, 11, 19, 8, 9, 10, 8, 9, 9, 10, 7, 10, 8, 10, 10, 15, 19, 8, 8, 8, 11, 9, 15, 7, 12, 9, 9, 19, 12, 8, 9, 10, 9, 9, 8, 10, 10, 11, 10, 13, 9, 13, 7, 11, 11, 8, 11, 10, 9, 10, 9, 8, 10, 7, 8, 16, 9, 8, 16, 9, 13, 11, 8, 20, 12, 8, 15, 9, 12, 9, 11, 8, 7, 24, 17, 12, 9, 14, 11, 16, 9, 17, 14, 8, 9, 10, 9, 9, 8, 9, 12, 10, 9, 8, 9, 10, 9, 15, 13, 15, 7, 7, 9, 7, 9, 9, 10, 12, 8, 8, 16, 13, 8, 10, 9, 9, 8, 8, 8, 11, 9, 9, 10, 7, 10, 7, 9, 9, 10, 8, 17, 11, 9, 7, 8, 17, 15, 9, 9, 9, 8, 10, 21, 16, 10, 10, 9, 15, 7, 9, 11, 9, 11, 9, 10, 7, 18, 9, 8, 8, 8, 7, 8, 19, 13, 8, 14, 10, 17, 12, 7, 11, 8, 7, 11, 7, 11, 9, 9, 12, 8, 8, 9, 18, 9, 10, 8, 11, 9, 8, 10, 7, 8, 9, 9, 10, 8, 9, 11, 11, 9, 13, 9, 25, 11, 23, 10, 8, 17, 9, 11, 11, 10, 7, 19, 16, 8, 8, 7, 11, 10, 8, 10, 10, 21, 9, 13, 17, 11, 9, 8, 9, 7, 10, 10, 8, 7, 10, 10, 12, 9, 7, 8, 8, 10, 8, 11, 8, 12, 9, 10, 8, 11, 7, 18, 11, 12, 8, 12, 9, 15, 8, 9, 17, 8, 11, 9, 10, 15, 8, 13, 9, 12, 30, 12, 9, 9, 9, 7, 7, 11, 13, 11, 14, 11, 16, 8, 15, 11, 18, 24, 11, 8, 12, 10, 9, 20, 12, 10, 10, 11, 10, 16, 7, 16, 21, 17, 9, 7, 12, 7, 8, 17, 9, 17, 7, 13, 18, 19, 13, 17, 9, 11, 7, 20, 10, 14, 9, 7, 9, 9, 8, 9, 13, 15, 7, 19, 8, 10, 7, 11, 8, 7, 9, 12, 10, 10, 7, 8, 8, 8, 11, 7, 10, 11, 7, 11, 12, 7, 15, 11, 12, 10, 9, 10, 9, 18, 11, 8, 9, 9, 18, 11, 13, 8, 9, 13, 7, 9, 10, 8, 9, 9, 9, 17, 10, 11, 14, 24, 9, 12, 11, 8, 10, 9, 10, 7, 17, 10, 10, 15, 10, 9, 9, 17, 11, 13, 10, 11, 16, 8, 9, 7, 9, 7, 10, 8, 8, 10, 10, 7, 9, 15, 10, 7, 9, 9, 10, 12, 9, 10, 8, 12, 9, 13, 12, 9, 8, 9, 9, 10, 12, 8, 17, 7, 7, 12, 10, 10, 8, 9, 9, 7, 9, 16, 8, 7, 8, 9, 11, 12, 9, 8, 9, 18, 12, 15, 7, 9, 11, 8, 9, 13, 17, 10, 16, 7, 13, 9, 11, 12, 13, 10, 17, 10, 14, 9, 11, 17, 9, 9, 8, 10, 16, 11, 13, 16, 8, 18, 9, 17, 9, 11, 8, 11, 9, 9, 10, 15, 12, 8, 8, 7, 12, 11, 8, 8, 8, 20, 11, 13, 11, 8, 9, 8, 8, 11, 9, 9, 13, 12, 19, 19, 9, 9, 11, 9, 19, 11, 8, 8, 7, 10, 8, 13, 8, 9, 9, 10, 11, 11, 21, 14, 10, 11, 9, 10, 7, 10, 11, 9, 6, 7, 7, 9, 13, 9, 10, 10, 12, 5, 10, 9, 9, 36, 14, 7, 9, 13, 9, 8, 11, 12, 15, 14, 9, 11, 9, 10, 12, 13, 10, 17, 9, 9, 12, 10, 9, 9, 10, 10, 12, 15, 15, 8, 11, 7, 9, 11, 10, 10, 8, 10, 9, 11, 8, 9, 3, 8, 10, 13, 16, 7, 3, 19, 14, 10, 11, 10, 18, 9, 17, 10, 9, 8, 11, 9, 8, 9, 8, 9, 10, 18, 10, 8, 14, 19, 7, 12, 9, 23, 14, 9, 7, 7, 8, 8, 8, 10, 9, 11, 10, 11, 7, 18, 9, 10, 8, 10, 8, 10, 8, 8, 12, 9, 12, 7, 8, 8, 9, 10, 9, 11, 11, 10, 10, 12, 8, 14, 11, 10, 12, 17, 17, 11, 18, 7, 11, 10, 20, 12, 7, 8, 17, 10, 12, 7, 12, 17, 7, 17, 8, 15, 12, 13, 7, 12, 10, 7, 10, 9, 10, 13, 9, 9, 9, 11, 11, 10, 15, 13, 7, 9, 8, 11, 9, 8, 11, 7, 13, 11, 8, 17, 9, 8, 10, 9, 10, 9, 12, 11, 8, 10, 14, 9, 3, 8, 10, 11, 8, 9, 15, 10, 18, 11, 7, 8, 14, 12, 10, 13, 10, 12, 17, 12, 8, 11, 9, 7, 7, 26, 8, 8, 12, 8, 15, 11, 10, 15, 18, 8, 7, 17, 17, 11, 14, 8, 8, 12, 10, 8, 9, 8, 9, 9, 6, 8, 10, 9, 13, 9, 8, 15, 13, 9, 9, 17, 9, 8, 6, 8, 8, 8, 10, 17, 10, 9, 20, 8, 9, 13, 9, 8, 10, 11, 9, 7, 17, 11, 11, 11, 15, 11, 12, 10, 10, 9, 9, 10, 7, 13, 9, 7, 10, 8, 10, 9, 13, 9, 7, 11, 9, 9, 8, 9, 8, 10, 12, 10, 14, 11, 18, 13, 8, 7, 8, 10, 17, 19, 10, 11, 21, 9, 10, 8, 9, 8, 10, 10, 12, 13, 7, 9, 11, 7, 10, 8, 9, 8, 11, 10, 8, 8, 8, 8, 8, 9, 8, 7, 15, 9, 8, 8, 15, 10, 8, 9, 11, 9, 7, 12, 8, 7, 7, 10, 13, 8, 10, 8, 17, 7, 9, 8, 9, 15, 9, 7, 10, 10, 9, 8, 17, 16, 9, 15, 6, 15, 10, 10, 10, 7, 12, 9, 9, 16, 9, 9, 10, 10, 10, 14, 9, 11, 10, 13, 7, 10, 8, 9, 12, 8, 9, 8, 11, 20, 9, 11, 19, 10, 9, 9, 14, 10, 7, 11, 9, 13, 8, 17, 10, 22, 14, 9, 7, 14, 8, 10, 9, 13, 13, 10, 17, 11, 13, 8, 10, 9, 9, 8, 7, 10, 10, 11, 23, 10, 9, 10, 8, 10, 14, 11, 7, 8, 8, 8, 8, 10, 9, 8, 8, 9, 19, 12, 14, 10, 16, 11, 30, 11, 12, 9, 11, 9, 8, 14, 8, 13, 8, 16, 11, 9, 8, 9, 21, 11, 8, 6, 8, 17, 11, 9, 9, 19, 13, 16, 12, 9, 11, 17, 10, 19, 13, 6, 8, 13, 8, 8, 18, 11, 10, 9, 8, 9, 8, 10, 9, 9, 7, 18, 8, 9, 12, 8, 9, 10, 10, 10, 9, 15, 9, 17, 11, 7, 12, 8, 8, 12, 10, 13, 8, 8, 15, 13, 11, 11, 19, 9, 8, 9, 9, 9, 9, 10, 9, 25, 13, 17, 10, 7, 12, 8, 16, 7, 8, 8, 8, 8, 10, 15, 13, 9, 9, 10, 11, 15, 10, 16, 10, 8, 8, 11, 7, 11, 7, 9, 28, 10, 9, 7, 13, 8, 8, 7, 10, 9, 8, 13, 7, 10, 8, 8, 13, 9, 7, 9, 11, 10, 9, 8, 9, 34, 8, 10, 11, 10, 10, 10, 11, 8, 9, 10, 10, 13, 13, 11, 10, 10, 13, 7, 27, 9, 23, 14, 10, 17, 6, 9, 12, 18, 9, 11, 8, 11, 8, 7, 10, 7, 7, 9, 10, 9, 9, 11, 12, 16, 10, 17, 8, 9, 10, 9, 17, 11, 9, 10, 15, 11, 8, 8, 12, 10, 7, 9, 7, 13, 7, 9, 10, 9, 9, 11, 8, 14, 10, 7, 9, 10, 12, 21, 9, 8, 9, 12, 10, 8, 7, 8, 8, 8, 8, 13, 8, 15, 8, 9, 10, 8, 8, 13, 7, 11, 8, 9, 9, 9, 14, 7, 17, 6, 9, 8, 7, 12, 9, 8, 8, 16, 6, 11, 10, 8, 7, 9, 8, 8, 7, 9, 8, 17, 8, 9, 8, 11, 11, 11, 14, 8, 12, 10, 19, 12, 13, 9, 8, 9, 11, 8, 11, 9, 9, 8, 12, 13, 10, 8, 11, 20, 13, 11, 10, 9, 11, 15, 9, 11, 9, 8, 8, 10, 8, 11, 12, 16, 7, 14, 9, 7, 8, 13, 11, 11, 15, 7, 8, 10, 8, 13, 7, 17, 11, 15, 9, 11, 10, 9, 10, 14, 15, 11, 9, 11, 11, 17, 10, 9, 7, 8, 9, 11, 7, 9, 14, 10, 12, 20, 7, 7, 9, 8, 11, 10, 10, 14, 17, 10, 10, 7, 7, 19, 11, 11, 7, 7, 17, 9, 10, 9, 11, 11, 8, 11, 9, 9, 8, 11, 9, 7, 9, 12, 12, 14, 9, 9, 14, 13, 7, 13, 17, 9, 9, 8, 7, 13, 10, 10, 10, 12, 13, 15, 13, 12, 9, 10, 8, 13, 8, 7, 8, 13, 9, 8, 10, 10, 7, 13, 10, 8, 8, 9, 8, 10, 8, 8, 11, 8, 7, 7, 7, 9, 13, 8, 8, 15, 10, 8, 8, 9, 11, 17, 10, 10, 12, 13, 14, 12, 12, 10, 10, 8, 9, 7, 10, 10, 8, 9, 8, 9, 8, 7, 6, 8, 8, 8, 8, 6, 9, 9, 9, 8, 8, 8, 11, 7, 9, 10, 9, 8, 13, 10, 8, 13, 15, 8, 15, 9, 11, 7, 15, 12, 7, 9, 9, 9, 13, 11, 29, 8, 8, 13, 10, 8, 19, 11, 8, 15, 8, 17, 10, 17, 8, 9, 8, 11, 11, 14, 11, 9, 10, 10, 9, 9, 12, 10, 9, 13, 21, 11, 9, 21, 22, 8, 12, 8, 11, 8, 18, 14, 10, 12, 12, 8, 10, 10, 11, 15, 15, 9, 9, 11, 16, 9, 11, 9, 9, 9, 9, 8, 14, 9, 8, 10, 10, 8, 8, 8, 10, 10, 8, 9, 8, 20, 9, 11, 9, 12, 10, 13, 6, 9, 15, 11, 11, 10, 17, 9, 9, 10, 9, 8, 10, 8, 8, 15, 8, 10, 23, 19, 8, 8, 17, 8, 7, 8, 12, 14, 16, 16, 10, 8, 11, 18, 10, 11, 8, 13, 11, 8, 9, 11, 9, 11, 10, 11, 10, 9, 9, 10, 8, 8, 11, 11, 10, 13, 20, 9, 11, 10, 9, 8, 18, 11, 8, 11, 15, 11, 9, 10, 8, 9, 8, 10, 15, 8, 11, 15, 11, 9, 15, 9, 13, 11, 17, 14, 8, 19, 9, 9, 9, 12, 20, 10, 10, 10, 8, 10, 8, 13, 10, 15, 9, 9, 15, 12, 8, 12, 27, 9, 9, 11, 10, 12, 8, 8, 13, 10, 18, 9, 18, 11, 7, 13, 11, 11, 10, 10, 11, 11, 14, 7, 11, 16, 8, 11, 6, 8, 10, 7, 9, 9, 19, 9, 11, 10, 12, 9, 9, 8, 8, 11, 11, 9, 9, 8, 19, 12, 11, 7, 9, 10, 7, 8, 8, 9, 9, 9, 10, 10, 9, 10, 11, 13, 10, 9, 8, 14, 26, 8, 13, 9, 11, 8, 15, 10, 21, 11, 10, 9, 9, 19, 8, 13, 11, 17, 9, 16, 9, 17, 10, 7, 8, 7, 12, 10, 16, 9, 11, 7, 9, 9, 8, 18, 7, 8, 9, 8, 10, 16, 8, 12, 7, 9, 23, 12, 11, 11, 10, 16, 10, 16, 10, 8, 9, 7, 8, 8, 9, 20, 13, 13, 10, 10, 12, 10, 8, 7, 8, 13, 9, 10, 12, 8, 9, 12, 15, 9, 23, 10, 16, 15, 10, 10, 13, 9, 15, 16, 10, 16, 9, 10, 8, 8, 20, 11, 14, 8, 9, 12, 15, 8, 11, 8, 14, 10, 9, 12, 8, 10, 11, 10, 10, 7, 7, 12, 9, 15, 9, 11, 7, 18, 8, 8, 9, 12, 7, 10, 16, 8, 8, 13, 7, 13, 9, 9, 11, 11, 10, 17, 9, 13, 11, 8, 14, 15, 9, 9, 10, 15, 8, 11, 8, 7, 12, 10, 8, 9, 11, 9, 9, 9, 11, 11, 15, 7, 10, 10, 8, 8, 10, 9, 11, 9, 11, 10, 9, 9, 13, 11, 8, 10, 12, 8, 10, 11, 7, 10, 10, 15, 16, 8, 9, 10, 17, 11, 10, 7, 18, 10, 17, 9, 10, 16, 17, 10, 14, 17, 10, 7, 8, 8, 9, 18, 16, 11, 10, 17, 17, 8, 12, 21, 11, 8, 8, 11, 10, 15, 15, 17, 13, 13, 7, 11, 8, 10, 15, 8, 10, 10, 8, 17, 16, 9, 8, 8, 8, 18, 8, 9, 9, 15, 8, 8, 11, 10, 6, 11, 8, 11, 9, 10, 9, 8, 11, 9, 8, 10, 8, 9, 15, 9, 8, 8, 8, 9, 11, 8, 8, 9, 9, 9, 8, 10, 10, 8, 10, 16, 9, 11, 10, 10, 11, 9, 19, 11, 7, 9, 8, 9, 8, 10, 8, 9, 14, 7, 8, 13, 11, 8, 9, 7, 15, 9, 8, 10, 9, 9, 11, 11, 11, 10, 16, 8, 7, 10, 13, 10, 9, 12, 13, 8, 7, 9, 12, 9, 9, 10, 8, 17, 13, 9, 10, 8, 17, 9, 8, 8, 9, 11, 11, 15, 7, 8, 17, 14, 18, 11, 9, 9, 13, 13, 9, 10, 7, 10, 9, 12, 13, 10, 13, 10, 9, 8, 9, 8, 11, 7, 11, 9, 9, 11, 16, 10, 7, 9, 9, 9, 8, 13, 7, 13, 8, 21, 7, 9, 11, 9, 9, 10, 17, 7, 8, 16, 7, 10, 8, 11, 10, 8, 8, 11, 9, 8, 7, 8, 8, 16, 10, 8, 10, 8, 10, 10, 13, 15, 7, 9, 10, 10, 7, 13, 8, 11, 9, 7, 18, 12, 10, 9, 11, 18, 11, 10, 8, 16, 10, 11, 14, 8, 8, 9, 11, 18, 8, 9, 11, 9, 10, 8, 17, 11, 7, 10, 13, 19, 8, 8, 7, 11, 9, 9, 12, 7, 10, 9, 10, 9, 8, 8, 13, 21, 8, 7, 9, 9, 17, 9, 11, 10, 23, 9, 10, 9, 18, 8, 10, 11, 8, 13, 10, 11, 15, 9, 8, 12, 10, 9, 14, 7, 14, 10, 7, 11, 9, 11, 13, 11, 10, 9, 9, 12, 10, 11, 12, 9, 9, 9, 11, 8, 17, 11, 12, 10, 19, 10, 15, 11, 18, 11, 10, 13, 9, 10, 10, 11, 17, 3, 11, 10, 8, 11, 18, 10, 12, 13, 9, 10, 12, 8, 8, 11, 8, 11, 8, 10, 7, 9, 18, 9, 11, 10, 8, 9, 9, 9, 10, 8, 8, 13, 19, 7, 19, 9, 8, 11, 8, 9, 10, 9, 10, 10, 8, 8, 9, 7, 8, 15, 9, 18, 7, 8, 11, 9, 12, 9, 9, 9, 9, 11, 17, 12, 8, 12, 10, 14, 9, 10, 17, 13, 10, 9, 7, 9, 9, 14, 19, 8, 8, 9, 8, 9, 11, 13, 13, 8, 8, 8, 8, 9, 7, 11, 10, 9, 8, 9, 10, 18, 8, 10, 11, 9, 8, 10, 14, 15, 9, 8, 10, 8, 9, 9, 7, 11, 9, 7, 10, 18, 8, 17, 10, 12, 8, 16, 9, 12, 12, 10, 11, 16, 9, 12, 10, 9, 9, 10, 9, 10, 16, 12, 10, 9, 9, 12, 8, 17, 8, 9, 13, 8, 10, 10, 8, 12, 7, 9, 12, 15, 9, 9, 6, 15, 8, 9, 10, 10, 9, 8, 10, 12, 10, 11, 10, 17, 14, 9, 8, 10, 16, 10, 9, 7, 12, 10, 8, 17, 8, 9, 7, 10, 9, 10, 11, 7, 11, 7, 14, 11, 15, 9, 16, 20, 21, 10, 9, 8, 8, 12, 17, 12, 15, 9, 16, 8, 8, 17, 12, 12, 9, 10, 8, 9, 12, 13, 8, 8, 10, 9, 10, 5, 10, 9, 9, 9, 11, 13, 10, 11, 9, 8, 10, 8, 13, 7, 8, 8, 8, 10, 10, 13, 9, 21, 9, 8, 10, 7, 9, 10, 16, 10, 9, 18, 10, 10, 10, 16, 17, 18, 9, 12, 12, 13, 8, 13, 12, 11, 10, 7, 10, 8, 10, 9, 14, 14, 9, 7, 13, 9, 9, 10, 6, 9, 9, 14, 9, 10, 13, 12, 7, 8, 10, 13, 8, 11, 9, 20, 9, 10, 11, 12, 9, 9, 12, 9, 12, 10, 10, 19, 9, 9, 8, 8, 13, 13, 9, 10, 8, 16, 17, 9, 8, 10, 9, 13, 6, 7, 9, 11, 9, 8, 29, 8, 9, 8, 10, 8, 23, 18, 9, 7, 15, 11, 11, 10, 10, 15, 7, 15, 7, 11, 9, 14, 9, 10, 14, 9, 9, 8, 18, 21, 8, 11, 11, 8, 13, 10, 7, 9, 12, 13, 23, 16, 10, 9, 8, 9, 11, 17, 8, 10, 10, 10, 9, 8, 9, 9, 9, 8, 8, 16, 8, 9, 9, 12, 17, 9, 17, 10, 8, 8, 9, 9, 11, 17, 10, 9, 9, 9, 8, 17, 16, 17, 12, 16, 13, 8, 9, 12, 10, 9, 10, 25, 13, 11, 15, 7, 11, 8, 8, 9, 10, 10, 9, 9, 9, 14, 15, 7, 11, 11, 11, 10, 15, 9, 10, 17, 11, 17, 21, 8, 8, 22, 11, 8, 12, 6, 9, 13, 10, 13, 13, 11, 14, 7, 8, 9, 9, 10, 16, 8, 7, 10, 10, 7, 7, 9, 9, 10, 9, 19, 11, 9, 8, 10, 11, 10, 15, 18, 11, 9, 9, 18, 8, 11, 7, 7, 8, 8, 15, 8, 9, 19, 7, 16, 9, 15, 10, 10, 20, 9, 11, 8, 15, 9, 15, 8, 17, 12, 9, 17, 20, 9, 10, 9, 8, 11, 8, 9, 10, 9, 9, 17, 10, 8, 10, 8, 12, 9, 9, 11, 9, 9, 7, 7, 19, 16, 7, 12, 7, 8, 7, 8, 12, 10, 15, 15, 12, 15, 8, 8, 9, 9, 13, 9, 9, 8, 11, 10, 7, 9, 17, 18, 7, 13, 8, 14, 13, 12, 10, 9, 10, 7, 10, 10, 9, 9, 8, 7, 11, 8, 17, 8, 10, 13, 10, 9, 15, 8, 10, 9, 12, 10, 10, 10, 9, 7, 10, 9, 11, 10, 10, 16, 22, 8, 8, 8, 11, 13, 9, 10, 11, 9, 11, 9, 9, 13, 9, 13, 8, 11, 9, 13, 9, 11, 10, 14, 9, 9, 9, 13, 9, 9, 9, 10, 8, 10, 7, 7, 8, 8, 9, 17, 9, 9, 9, 20, 13, 9, 8, 7, 11, 8, 7, 8, 10, 13, 9, 8, 24, 12, 15, 7, 11, 9, 10, 12, 10, 10, 10, 14, 9, 11, 9, 8, 11, 13, 11, 13, 15, 9, 7, 8, 8, 10, 10, 9, 11, 9, 11, 14, 15, 17, 14, 7, 10, 15, 14, 9, 9, 8, 17, 15, 13, 9, 8, 16, 16, 9, 9, 9, 9, 9, 8, 8, 8, 9, 11, 23, 10, 12, 11, 12, 27, 8, 8, 11, 11, 10, 8, 13, 8, 8, 9, 9, 11, 12, 10, 8, 9, 8, 10, 11, 10, 7, 9, 10, 11, 10, 7, 9, 17, 9, 15, 8, 11, 15, 11, 8, 12, 8, 8, 12, 9, 8, 10, 9, 7, 13, 13, 11, 10, 8, 13, 10, 7, 8, 11, 10, 9, 12, 10, 17, 7, 9, 9, 8, 6, 8, 10, 8, 15, 12, 8, 9, 11, 19, 10, 9, 8, 11, 11, 11, 9, 13, 13, 7, 9, 7, 16, 8, 11, 11, 9, 9, 15, 19, 8, 16, 9, 10, 10, 7, 18, 8, 7, 9, 16, 9, 8, 10, 11, 9, 29, 7, 9, 10, 9, 8, 13, 11, 13, 10, 8, 9, 10, 9, 11, 13, 8, 11, 8, 9, 13, 8, 8, 17, 6, 12, 10, 9, 12, 14, 10, 8, 11, 9, 9, 10, 11, 15, 8, 14, 9, 9, 8, 7, 11, 8, 9, 12, 7, 8, 11, 9, 10, 11, 10, 16, 10, 14, 10, 17, 9, 9, 10, 9, 18, 16, 8, 8, 9, 13, 9, 9, 8, 10, 10, 15, 7, 12, 8, 9, 6, 9, 14, 14, 9, 9, 8, 9, 9, 18, 8, 11, 9, 11, 14, 13, 17, 8, 9, 11, 20, 13, 10, 23, 15, 9, 8, 9, 10, 12, 9, 7, 10, 17, 9, 10, 9, 8, 9, 9, 7, 13, 15, 18, 8, 9, 10, 8, 7, 10, 9, 8, 8, 9, 7, 11, 9, 7, 11, 8, 9, 9, 9, 8, 14, 13, 10, 15, 11, 7, 9, 7, 10, 9, 17, 8, 7, 11, 12, 8, 12, 10, 11, 7, 8, 9, 19, 8, 8, 13, 8, 8, 8, 9, 10, 8, 9, 8, 8, 10, 10, 10, 11, 18, 7, 19, 10, 8, 13, 10, 13, 9, 9, 12, 7, 9, 9, 9, 11, 9, 8, 9, 22, 9, 8, 8, 8, 8, 9, 13, 10, 10, 14, 10, 23, 9, 8, 15, 10, 8, 9, 7, 8, 7, 13, 12, 8, 14, 11, 10, 12, 13, 9, 7, 8, 9, 8, 7, 6, 10, 13, 10, 9, 13, 9, 17, 10, 8, 9, 10, 9, 13, 11, 12, 13, 9, 10, 9, 10, 11, 8, 7, 10, 10, 9, 12, 7, 10, 15, 13, 14, 7, 12, 9, 11, 14, 13, 6, 8, 26, 13, 16, 10, 17, 13, 11, 10, 10, 11, 9, 15, 7, 10, 8, 8, 10, 9, 8, 8, 16, 10, 17, 24, 8, 7, 8, 8, 8, 11, 9, 9, 17, 11, 19, 11, 8, 10, 14, 8, 19, 10, 9, 9, 11, 15, 10, 9, 8, 11, 12, 8, 11, 18, 10, 9, 9, 8, 11, 6, 8, 13, 7, 18, 10, 7, 17, 12, 7, 8, 10, 8, 11, 12, 9, 9, 7, 7, 10, 9, 7, 19, 17, 18, 9, 9, 8, 9, 9, 6, 9, 10, 9, 10, 9, 9, 7, 10, 8, 9, 13, 9, 8, 7, 8, 10, 11, 9, 8, 8, 9, 11, 9, 7, 9, 10, 8, 19, 8, 14, 9, 6, 9, 11, 8, 9, 8, 13, 9, 12, 9, 9, 11, 10, 8, 8, 12, 8, 8, 13, 11, 13, 13, 11, 7, 10, 7, 27, 11, 15, 9, 7, 8, 8, 11, 7, 15, 8, 7, 9, 11, 9, 10, 9, 14, 9, 16, 8, 8, 12, 9, 8, 8, 9, 7, 9, 12, 10, 14, 8, 7, 7, 7, 14, 17, 9, 11, 10, 8, 9, 8, 8, 19, 11, 9, 9, 17, 17, 9, 10, 9, 17, 21, 11, 8, 8, 7, 15, 9, 9, 8, 17, 25, 9, 17, 10, 27, 13, 10, 11, 9, 11, 8, 17, 9, 8, 11, 9, 12, 11, 12, 7, 10, 8, 10, 8, 11, 8, 9, 8, 8, 15, 14, 9, 11, 9, 13, 11, 14, 8, 11, 17, 9, 7, 9, 8, 10, 8, 15, 12, 7, 7, 17, 7, 10, 20, 10, 9, 7, 8, 9, 16, 12, 19, 9, 17, 10, 8, 11, 10, 17, 17, 9, 17, 19, 9, 30, 8, 9, 9, 8, 23, 9, 10, 9, 10, 7, 9, 8, 8, 7, 9, 11, 10, 8, 12, 9, 11, 9, 16, 7, 11, 8, 9, 11, 9, 13, 10, 9, 9, 10, 13, 10, 18, 9, 11, 11, 19, 7, 11, 10, 14, 8, 12, 14, 11, 9, 9, 8, 10, 8, 8, 13, 10, 11, 10, 9, 9, 9, 8, 9, 8, 10, 8, 10, 12, 20, 9, 13, 8, 15, 10, 9, 9, 9, 9, 9, 10, 8, 9, 11, 11, 8, 8, 12, 9, 8, 17, 23, 9, 11, 13, 9, 11, 13, 13, 13, 13, 9, 12, 9, 10, 8, 10, 8, 13, 9, 7, 10, 9, 17, 9, 9, 8, 7, 13, 9, 13, 9, 7, 9, 10, 12, 10, 16, 14, 9, 10, 9, 8, 14, 8, 7, 11, 13, 11, 13, 11, 15, 10, 8, 14, 10, 16, 8, 9, 12, 11, 14, 9, 18, 17, 8, 9, 8, 11, 8, 9, 14, 8, 8, 10, 22, 10, 24, 13, 10, 9, 10, 12, 9, 10, 10, 11, 15, 15, 9, 10, 10, 19, 9, 10, 10, 17, 12, 15, 16, 8, 13, 12, 27, 17, 9, 11, 7, 9, 10, 13, 10, 8, 10, 13, 11, 13, 18, 9, 17, 11, 10, 8, 8, 17, 6, 8, 16, 9, 11, 8, 17, 18, 11, 9, 8, 16, 11, 9, 8, 11, 13, 9, 14, 13, 11, 7, 10, 13, 8, 8, 7, 7, 9, 8, 13, 9, 22, 15, 15, 8, 9, 9, 9, 7, 12, 8, 11, 9, 8, 9, 9, 10, 9, 9, 11, 10, 10, 7, 10, 9, 11, 23, 12, 15, 9, 9, 9, 9, 9, 8, 14, 10, 9, 9, 10, 9, 9, 18, 12, 8, 9, 9, 23, 10, 8, 10, 8, 9, 9, 8, 8, 8, 8, 16, 7, 12, 10, 9, 13, 9, 9, 11, 12, 12, 10, 9, 9, 9, 8, 17, 23, 9, 14, 11, 8, 15, 10, 10, 7, 14, 7, 8, 12, 10, 11, 10, 9, 8, 10, 7, 18, 17, 11, 8, 8, 17, 11, 7, 8, 10, 15, 11, 8, 9, 7, 11, 16, 10, 10, 10, 9, 17, 10, 11, 8, 8, 13, 10, 10, 7, 8, 8, 7, 9, 13, 11, 10, 15, 9, 10, 10, 13, 9, 8, 10, 9, 11, 8, 12, 12, 10, 11, 9, 16, 10, 10, 9, 14, 10, 7, 8, 12, 8, 8, 9, 8, 9, 18, 17, 7, 8, 10, 20, 8, 10, 9, 7, 8, 11, 7, 13, 8, 9, 8, 15, 17, 12, 8, 8, 10, 10, 19, 8, 18, 9, 13, 19, 9, 14, 17, 14, 15, 8, 11, 9, 8, 17, 9, 7, 9, 10, 9, 17, 10, 10, 13, 10, 8, 17, 10, 20, 10, 10, 11, 10, 9, 10, 14, 12, 9, 13, 9, 14, 14, 11, 9, 17, 7, 8, 8, 7, 9, 11, 10, 10, 9, 9, 12, 10, 11, 8, 9, 8, 9, 12, 9, 8, 7, 8, 10, 13, 6, 10, 8, 9, 12, 10, 13, 7, 8, 8, 13, 8, 8, 13, 10, 17, 14, 6, 11, 9, 10, 8, 7, 13, 10, 14, 9, 7, 10, 11, 8, 8, 8, 14, 24, 12, 9, 8, 16, 13, 11, 10, 8, 11, 9, 11, 10, 13, 9, 15, 8, 14, 9, 8, 9, 8, 9, 12, 18, 11, 8, 9, 7, 9, 10, 10, 12, 11, 8, 10, 10, 7, 8, 7, 10, 8, 12, 20, 17, 10, 13, 10, 11, 9, 12, 10, 22, 11, 7, 8, 9, 18, 9, 9, 16, 7, 10, 15, 7, 10, 8, 8, 8, 10, 20, 9, 9, 8, 13, 9, 13, 9, 7, 13, 7, 8, 8, 9, 10, 7, 15, 8, 16, 9, 8, 14, 7, 9, 9, 8, 7, 7, 9, 9, 10, 8, 11, 9, 9, 12, 10, 16, 7, 9, 8, 10, 8, 7, 11, 9, 15, 9, 10, 9, 9, 8, 9, 7, 11, 9, 8, 19, 7, 19, 11, 10, 7, 14, 11, 7, 9, 8, 7, 8, 9, 10, 11, 7, 8, 11, 10, 11, 13, 7, 9, 8, 12, 9, 8, 9, 9, 9, 11, 8, 10, 8, 9, 8, 15, 8, 10, 22, 16, 10, 11, 8, 11, 9, 8, 13, 9, 8, 11, 9, 10, 13, 11, 10, 12, 8, 14, 10, 10, 15, 8, 7, 9, 9, 13, 8, 9, 9, 13, 8
'y' sizes: 12816
