In [14]:
# Importar las librerías necesarias
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import SGD

# Definir el modelo de la red convolucional
model = Sequential([
    Conv2D(filters=6, kernel_size=(3, 3), activation='relu', input_shape=(3, 3, 3)),
    Flatten(),
    Dense(units=2, activation='softmax')
])

# Compilar el modelo
model.compile(optimizer=SGD(learning_rate=0.01, momentum=0.9),
              loss=SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

# Definir datos de ejemplo (2 matrices 3x3 con 3 canales)
data = np.array([
    [[[0, 1, 0], [1, 0, 1], [0, 1, 0]],
     [[1, 0, 0], [0, 1, 0], [1, 0, 0]],
     [[0, 1, 0], [1, 0, 1], [0, 1, 0]]],
    
    [[[1, 0, 1], [0, 1, 0], [1, 0, 1]],
     [[0, 1, 0], [1, 0, 1], [0, 1, 0]],
     [[1, 0, 1], [0, 1, 0], [1, 0, 1]]]
], dtype=np.float32)

with np.printoptions(threshold=np.inf):
    print(data)

# Etiquetas de ejemplo (clases)
labels = np.array([0, 1], dtype=int)

print(data.shape)
print(labels.shape)

# Entrenar el modelo
model.fit(data, labels, epochs=10)

# Prueba con un nuevo dato
test_data = np.array([[[[0, 1, 0], [1, 0, 1], [0, 1, 0]],
                       [[1, 0, 0], [0, 1, 0], [1, 0, 0]],
                       [[0, 1, 0], [1, 0, 1], [0, 1, 0]]]], dtype=np.float32)

predicted = model.predict(test_data)
predicted_class = np.argmax(predicted, axis=1)
print(f"Predicted class: {predicted_class[0]}")


[[[[0. 1. 0.]
   [1. 0. 1.]
   [0. 1. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [1. 0. 0.]]

  [[0. 1. 0.]
   [1. 0. 1.]
   [0. 1. 0.]]]


 [[[1. 0. 1.]
   [0. 1. 0.]
   [1. 0. 1.]]

  [[0. 1. 0.]
   [1. 0. 1.]
   [0. 1. 0.]]

  [[1. 0. 1.]
   [0. 1. 0.]
   [1. 0. 1.]]]]
(2, 3, 3, 3)
(2,)
Epoch 1/10


c:\Users\Hans\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 559ms/step - accuracy: 0.5000 - loss: 0.8348
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.8216
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7971
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7639
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7241
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6855
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6535
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6282
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6033
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.5784
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Predicted class: 0
